In [342]:
pwd

'C:\\Users\\mocid\\Ironhack\\labs\\projects\\Project1'

# Possible questions:

1 Crossing column Country(Australia) with Age to check the age distribution of Australians attacked by sharks

2 Crossing column Fatal(Y/N) with Time to check when are sharks more prone to kill people

3 Crossing column Type[Provoked] with country to check what countries incite more shark attacks

4 Crossing Country [USA], Year [1995-2018] and Sex[F] to check what what year did women have the most shark-related accidents in the USA

#### Columns I'll be using:
1 Country, Age
2 Fatal (Y/N), Time
3 Type, Country
4 Injury, Activity
5 Country, Year, Sex 

Overall, columns to clean: 
##### Country, Age, Fatal(Y/N), Time, Year, Sex, Type

In [328]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

https://github.com/Ironhack-data-bcn-oct-2023/project-I-pandas#readme

In [6]:
pd.set_option('display.max_columns', None)
sharks = pd.read_csv("C:/Users/mocid/Ironhack/labs/projects/Project1/attacks.csv",encoding='latin1')
sharks.sample(5)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
6312,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7819,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
sharks.head(5)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [8]:
sharks.tail(5)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Getting sum of those good ol informations:

### Table information

In [9]:
sharks.describe

<bound method NDFrame.describe of       Case Number         Date    Year        Type    Country  \
0      2018.06.25  25-Jun-2018  2018.0     Boating        USA
1      2018.06.18  18-Jun-2018  2018.0  Unprovoked        USA
2      2018.06.09  09-Jun-2018  2018.0     Invalid        USA
3      2018.06.08  08-Jun-2018  2018.0  Unprovoked  AUSTRALIA
4      2018.06.04  04-Jun-2018  2018.0    Provoked     MEXICO
...           ...          ...     ...         ...        ...
25718         NaN          NaN     NaN         NaN        NaN
25719         NaN          NaN     NaN         NaN        NaN
25720         NaN          NaN     NaN         NaN        NaN
25721         NaN          NaN     NaN         NaN        NaN
25722          xx          NaN     NaN         NaN        NaN

                  Area                        Location     Activity  \
0           California     Oceanside, San Diego County     Paddling
1              Georgia  St. Simon Island, Glynn County     Standing
2               Hawaii                    Habush, Oahu      Surfing
3      New South Wales              Arrawarra Headland      Surfing
4               Colima                        La Ticla  Free diving
...                ...                             ...          ...
25718              NaN                             NaN          NaN
25719              NaN                             NaN          NaN
25720              NaN                             NaN          NaN
25721              NaN                             NaN          NaN
25722              NaN                             NaN          NaN

                  Name Sex   Age  \
0          Julie Wolfe    F   57
1      Adyson McNeely     F   11
2          John Denges    M   48
3                 male    M  NaN
4       Gustavo Ramos     M  NaN
...                ...  ...  ...
25718              NaN  NaN  NaN
25719              NaN  NaN  NaN
25720              NaN  NaN  NaN
25721              NaN  NaN  NaN
25722              NaN  NaN  NaN

                                                  Injury Fatal (Y/N)  \
0      No injury to occupant, outrigger canoe and pad...           N
1                             Minor injury to left thigh           N
2           Injury to left lower leg from surfboard skeg           N
3                              Minor injury to lower leg           N
4      Lacerations to leg & hand shark PROVOKED INCIDENT           N
...                                                  ...         ...
25718                                                NaN         NaN
25719                                                NaN         NaN
25720                                                NaN         NaN
25721                                                NaN         NaN
25722                                                NaN         NaN

                Time         Species           Investigator or Source  \
0              18h00      White shark                R. Collier, GSAF
1      14h00  -15h00              NaN  K.McMurray, TrackingSharks.com
2              07h45              NaN  K.McMurray, TrackingSharks.com
3                NaN        2 m shark                  B. Myatt, GSAF
4                NaN  Tiger shark, 3m                       A .Kipper
...              ...              ...                             ...
25718            NaN              NaN                             NaN
25719            NaN              NaN                             NaN
25720            NaN              NaN                             NaN
25721            NaN              NaN                             NaN
25722            NaN              NaN                             NaN

                            pdf  \
0          2018.06.25-Wolfe.pdf
1        2018.06.18-McNeely.pdf
2         2018.06.09-Denges.pdf
3      2018.06.08-Arrawarra.pdf
4          2018.06.04-Ramos.pdf
...                         ...
25718                       NaN
25719                       NaN
25720                       NaN
25721                       NaN
25722                       NaN

                                            href formula  \
0      http://sharkattackfile.net/spreadsheets/pdf_di...
1      http://sharkattackfile.net/spreadsheets/pdf_di...
2      http://sharkattackfile.net/spreadsheets/pdf_di...
3      http://sharkattackfile.net/spreadsheets/pdf_di...
4      http://sharkattackfile.net/spreadsheets/pdf_di...
...                                                  ...
25718                                                NaN
25719                                                NaN
25720                                                NaN
25721                                                NaN
25722                                                NaN

                                                    href Case Number.1  \
0      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.25
1      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.18
2      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.09
3      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.08
4      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.04
...                                                  ...           ...
25718                                                NaN           NaN
25719                                                NaN           NaN
25720                                                NaN           NaN
25721                                                NaN           NaN
25722                                                NaN           NaN

      Case Number.2  original order Unnamed: 22 Unnamed: 23
0        2018.06.25          6303.0         NaN         NaN
1        2018.06.18          6302.0         NaN         NaN
2        2018.06.09          6301.0         NaN         NaN
3        2018.06.08          6300.0         NaN         NaN
4        2018.06.04          6299.0         NaN         NaN
...             ...             ...         ...         ...
25718           NaN             NaN         NaN         NaN
25719           NaN             NaN         NaN         NaN
25720           NaN             NaN         NaN         NaN
25721           NaN             NaN         NaN         NaN
25722           NaN             NaN         NaN         NaN

[25723 rows x 24 columns]>

In [10]:
sharks.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

### Cohesiveness of data

In [11]:
sharks.duplicated().sum()

19411

In [12]:
print("WHAT A MESSSSS:")
sharks.value_counts

WHAT A MESSSSS:

<bound method DataFrame.value_counts of       Case Number         Date    Year        Type    Country  \
0      2018.06.25  25-Jun-2018  2018.0     Boating        USA
1      2018.06.18  18-Jun-2018  2018.0  Unprovoked        USA
2      2018.06.09  09-Jun-2018  2018.0     Invalid        USA
3      2018.06.08  08-Jun-2018  2018.0  Unprovoked  AUSTRALIA
4      2018.06.04  04-Jun-2018  2018.0    Provoked     MEXICO
...           ...          ...     ...         ...        ...
25718         NaN          NaN     NaN         NaN        NaN
25719         NaN          NaN     NaN         NaN        NaN
25720         NaN          NaN     NaN         NaN        NaN
25721         NaN          NaN     NaN         NaN        NaN
25722          xx          NaN     NaN         NaN        NaN

                  Area                        Location     Activity  \
0           California     Oceanside, San Diego County     Paddling
1              Georgia  St. Simon Island, Glynn County     Standing
2               Hawaii                    Habush, Oahu      Surfing
3      New South Wales              Arrawarra Headland      Surfing
4               Colima                        La Ticla  Free diving
...                ...                             ...          ...
25718              NaN                             NaN          NaN
25719              NaN                             NaN          NaN
25720              NaN                             NaN          NaN
25721              NaN                             NaN          NaN
25722              NaN                             NaN          NaN

                  Name Sex   Age  \
0          Julie Wolfe    F   57
1      Adyson McNeely     F   11
2          John Denges    M   48
3                 male    M  NaN
4       Gustavo Ramos     M  NaN
...                ...  ...  ...
25718              NaN  NaN  NaN
25719              NaN  NaN  NaN
25720              NaN  NaN  NaN
25721              NaN  NaN  NaN
25722              NaN  NaN  NaN

                                                  Injury Fatal (Y/N)  \
0      No injury to occupant, outrigger canoe and pad...           N
1                             Minor injury to left thigh           N
2           Injury to left lower leg from surfboard skeg           N
3                              Minor injury to lower leg           N
4      Lacerations to leg & hand shark PROVOKED INCIDENT           N
...                                                  ...         ...
25718                                                NaN         NaN
25719                                                NaN         NaN
25720                                                NaN         NaN
25721                                                NaN         NaN
25722                                                NaN         NaN

                Time         Species           Investigator or Source  \
0              18h00      White shark                R. Collier, GSAF
1      14h00  -15h00              NaN  K.McMurray, TrackingSharks.com
2              07h45              NaN  K.McMurray, TrackingSharks.com
3                NaN        2 m shark                  B. Myatt, GSAF
4                NaN  Tiger shark, 3m                       A .Kipper
...              ...              ...                             ...
25718            NaN              NaN                             NaN
25719            NaN              NaN                             NaN
25720            NaN              NaN                             NaN
25721            NaN              NaN                             NaN
25722            NaN              NaN                             NaN

                            pdf  \
0          2018.06.25-Wolfe.pdf
1        2018.06.18-McNeely.pdf
2         2018.06.09-Denges.pdf
3      2018.06.08-Arrawarra.pdf
4          2018.06.04-Ramos.pdf
...                         ...
25718                       NaN
25719                       NaN
25720                       NaN
25721                       NaN
25722                       NaN

                                            href formula  \
0      http://sharkattackfile.net/spreadsheets/pdf_di...
1      http://sharkattackfile.net/spreadsheets/pdf_di...
2      http://sharkattackfile.net/spreadsheets/pdf_di...
3      http://sharkattackfile.net/spreadsheets/pdf_di...
4      http://sharkattackfile.net/spreadsheets/pdf_di...
...                                                  ...
25718                                                NaN
25719                                                NaN
25720                                                NaN
25721                                                NaN
25722                                                NaN

                                                    href Case Number.1  \
0      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.25
1      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.18
2      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.09
3      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.08
4      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.04
...                                                  ...           ...
25718                                                NaN           NaN
25719                                                NaN           NaN
25720                                                NaN           NaN
25721                                                NaN           NaN
25722                                                NaN           NaN

      Case Number.2  original order Unnamed: 22 Unnamed: 23
0        2018.06.25          6303.0         NaN         NaN
1        2018.06.18          6302.0         NaN         NaN
2        2018.06.09          6301.0         NaN         NaN
3        2018.06.08          6300.0         NaN         NaN
4        2018.06.04          6299.0         NaN         NaN
...             ...             ...         ...         ...
25718           NaN             NaN         NaN         NaN
25719           NaN             NaN         NaN         NaN
25720           NaN             NaN         NaN         NaN
25721           NaN             NaN         NaN         NaN
25722           NaN             NaN         NaN         NaN

[25723 rows x 24 columns]>

In [13]:
sharks.isna().sample(3)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
15758,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
18618,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
20816,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [14]:
sharks.isna().sum()

Case Number               17021
Date                      19421
Year                      19423
Type                      19425
Country                   19471
Area                      19876
Location                  19961
Activity                  19965
Name                      19631
Sex                       19986
Age                       22252
Injury                    19449
Fatal (Y/N)               19960
Time                      22775
Species                   22259
Investigator or Source    19438
pdf                       19421
href formula              19422
href                      19421
Case Number.1             19421
Case Number.2             19421
original order            19414
Unnamed: 22               25722
Unnamed: 23               25721
dtype: int64

### Information regarding values/variables

In [15]:
sharks.dtypes

Case Number                object
Date                       object
Year                      float64
Type                       object
Country                    object
Area                       object
Location                   object
Activity                   object
Name                       object
Sex                        object
Age                        object
Injury                     object
Fatal (Y/N)                object
Time                       object
Species                    object
Investigator or Source     object
pdf                        object
href formula               object
href                       object
Case Number.1              object
Case Number.2              object
original order            float64
Unnamed: 22                object
Unnamed: 23                object
dtype: object

#### Quantitative and Categorical variables:

In [16]:
sharks.dtypes
sharks_quant_vars = sharks.select_dtypes(include='float64')
sharks_quant_vars

         Year  original order
0      2018.0          6303.0
1      2018.0          6302.0
2      2018.0          6301.0
3      2018.0          6300.0
4      2018.0          6299.0
...       ...             ...
25718     NaN             NaN
25719     NaN             NaN
25720     NaN             NaN
25721     NaN             NaN
25722     NaN             NaN

[25723 rows x 2 columns]

In [17]:
sharks.dtypes
sharks_cat_vars = sharks.select_dtypes(include='object')
sharks_cat_vars

,Case Number,Date,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,NaN,NaN
1,2018.06.18,18-Jun-2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,NaN,NaN
2,2018.06.09,09-Jun-2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,NaN,NaN
3,2018.06.08,08-Jun-2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,NaN,NaN
4,2018.06.04,04-Jun-2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Cleaning "Country"

In [575]:
sharks_q1 = sharks.copy()

In [576]:
sharks_q1["Country"].unique()

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'ENGLAND', 'SOUTH AFRICA',
       'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS', 'NEW CALEDONIA',
       'ECUADOR', 'MALAYSIA', 'LIBYA', nan, 'CUBA', 'MAURITIUS',
       'NEW ZEALAND', 'SPAIN', 'SAMOA', 'SOLOMON ISLANDS', 'JAPAN',
       'EGYPT', 'ST HELENA, British overseas territory', 'COMOROS',
       'REUNION', 'FRENCH POLYNESIA', 'UNITED KINGDOM',
       'UNITED ARAB EMIRATES', 'PHILIPPINES', 'INDONESIA', 'CHINA',
       'COLUMBIA', 'CAPE VERDE', 'Fiji', 'DOMINICAN REPUBLIC',
       'CAYMAN ISLANDS', 'ARUBA', 'MOZAMBIQUE', 'FIJI', 'PUERTO RICO',
       'ITALY', 'ATLANTIC OCEAN', 'GREECE', 'ST. MARTIN', 'FRANCE',
       'PAPUA NEW GUINEA', 'TRINIDAD & TOBAGO', 'KIRIBATI', 'ISRAEL',
       'DIEGO GARCIA', 'TAIWAN', 'JAMAICA', 'PALESTINIAN TERRITORIES',
       'GUAM', 'SEYCHELLES', 'BELIZE', 'NIGERIA', 'TONGA', 'SCOTLAND',
       'CANADA', 'CROATIA', 'SAUDI ARABIA', 'CHILE', 'ANTIGUA', 'KENYA',
       'RUSSIA', 'TURKS & CAICOS', 'UNITED ARAB EMIRATES (UAE)', 'AZORES',
       'SOUTH KOREA', 'MALTA', 'VIETNAM', 'MADAGASCAR', 'PANAMA',
       'SOMALIA', 'NEVIS', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL',
       'YEMEN', 'GULF OF ADEN', 'Sierra Leone', 'ST. MAARTIN',
       'GRAND CAYMAN', 'Seychelles', 'LIBERIA', 'VANUATU', 'MEXICO ',
       'HONDURAS', 'VENEZUELA', 'SRI LANKA', ' TONGA', 'URUGUAY', 'INDIA',
       'MICRONESIA', 'CARIBBEAN SEA', 'OKINAWA', 'TANZANIA',
       'MARSHALL ISLANDS', 'EGYPT / ISRAEL', 'NORTHERN ARABIAN SEA',
       'HONG KONG', 'EL SALVADOR', 'ANGOLA', 'BERMUDA', 'MONTENEGRO',
       'IRAN', 'TUNISIA', 'NAMIBIA', 'NORTH ATLANTIC OCEAN', 'PORTUGAL',
       'SOUTH CHINA SEA', 'BANGLADESH', 'PALAU', 'WESTERN SAMOA',
       'PACIFIC OCEAN ', 'BRITISH ISLES', 'GRENADA', 'IRAQ', 'TURKEY',
       'SINGAPORE', 'NEW BRITAIN', 'SUDAN', 'JOHNSTON ISLAND',
       'SOUTH PACIFIC OCEAN', 'NEW GUINEA', 'RED SEA',
       'NORTH PACIFIC OCEAN', 'FEDERATED STATES OF MICRONESIA',
       'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES', 'MID ATLANTIC OCEAN',
       'PERSIAN GULF', 'RED SEA / INDIAN OCEAN', 'PACIFIC OCEAN',
       'NORTH SEA', 'NICARAGUA ', 'MALDIVE ISLANDS', 'AMERICAN SAMOA',
       'ANDAMAN / NICOBAR ISLANDAS', 'GABON', 'MAYOTTE',
       'NORTH ATLANTIC OCEAN ', 'THE BALKANS', 'SUDAN?', 'ARGENTINA',
       'MARTINIQUE', 'INDIAN OCEAN', 'GUATEMALA', 'NETHERLANDS ANTILLES',
       'NORTHERN MARIANA ISLANDS', 'IRAN / IRAQ', 'JAVA', 'SIERRA LEONE',
       ' PHILIPPINES', 'NICARAGUA', 'CENTRAL PACIFIC',
       'SOLOMON ISLANDS / VANUATU', 'SOUTHWEST PACIFIC OCEAN',
       'BAY OF BENGAL', 'MID-PACIFC OCEAN', 'SOUTH ATLANTIC OCEAN',
       'SLOVENIA', 'CURACAO', 'ICELAND', 'ITALY / CROATIA', 'BARBADOS',
       'MONACO', 'GUYANA', 'HAITI', 'SAN DOMINGO', 'IRELAND', 'KUWAIT',
       'YEMEN ', 'REUNION ISLAND', 'FALKLAND ISLANDS', 'CRETE', 'CYPRUS',
       'EGYPT ', 'WEST INDIES', 'BURMA', 'LEBANON', 'PARAGUAY',
       'BRITISH NEW GUINEA', 'CEYLON', 'OCEAN', 'GEORGIA', 'SYRIA',
       'TUVALU', 'INDIAN OCEAN?', 'GUINEA', 'ANDAMAN ISLANDS',
       'EQUATORIAL GUINEA / CAMEROON', 'COOK ISLANDS', 'TOBAGO', 'PERU',
       'AFRICA', 'ALGERIA', 'Coast of AFRICA', 'TASMAN SEA', 'GHANA',
       'GREENLAND', 'MEDITERRANEAN SEA', 'SWEDEN', 'ROATAN',
       'Between PORTUGAL & INDIA', 'DJIBOUTI', 'BAHREIN', 'KOREA',
       'RED SEA?', 'ASIA?', 'CEYLON (SRI LANKA)'], dtype=object)

In [577]:
#first off I'll make everything upper case jsut to be visually easier for me
sharks_q1["Country"] = sharks_q1["Country"].str.upper() #let's get this data uniform in terms of capitalization

In [578]:
sharks_q1["Country"].unique()

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'ENGLAND', 'SOUTH AFRICA',
       'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS', 'NEW CALEDONIA',
       'ECUADOR', 'MALAYSIA', 'LIBYA', nan, 'CUBA', 'MAURITIUS',
       'NEW ZEALAND', 'SPAIN', 'SAMOA', 'SOLOMON ISLANDS', 'JAPAN',
       'EGYPT', 'ST HELENA, BRITISH OVERSEAS TERRITORY', 'COMOROS',
       'REUNION', 'FRENCH POLYNESIA', 'UNITED KINGDOM',
       'UNITED ARAB EMIRATES', 'PHILIPPINES', 'INDONESIA', 'CHINA',
       'COLUMBIA', 'CAPE VERDE', 'FIJI', 'DOMINICAN REPUBLIC',
       'CAYMAN ISLANDS', 'ARUBA', 'MOZAMBIQUE', 'PUERTO RICO', 'ITALY',
       'ATLANTIC OCEAN', 'GREECE', 'ST. MARTIN', 'FRANCE',
       'PAPUA NEW GUINEA', 'TRINIDAD & TOBAGO', 'KIRIBATI', 'ISRAEL',
       'DIEGO GARCIA', 'TAIWAN', 'JAMAICA', 'PALESTINIAN TERRITORIES',
       'GUAM', 'SEYCHELLES', 'BELIZE', 'NIGERIA', 'TONGA', 'SCOTLAND',
       'CANADA', 'CROATIA', 'SAUDI ARABIA', 'CHILE', 'ANTIGUA', 'KENYA',
       'RUSSIA', 'TURKS & CAICOS', 'UNITED ARAB EMIRATES (UAE)', 'AZORES',
       'SOUTH KOREA', 'MALTA', 'VIETNAM', 'MADAGASCAR', 'PANAMA',
       'SOMALIA', 'NEVIS', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL',
       'YEMEN', 'GULF OF ADEN', 'SIERRA LEONE', 'ST. MAARTIN',
       'GRAND CAYMAN', 'LIBERIA', 'VANUATU', 'MEXICO ', 'HONDURAS',
       'VENEZUELA', 'SRI LANKA', ' TONGA', 'URUGUAY', 'INDIA',
       'MICRONESIA', 'CARIBBEAN SEA', 'OKINAWA', 'TANZANIA',
       'MARSHALL ISLANDS', 'EGYPT / ISRAEL', 'NORTHERN ARABIAN SEA',
       'HONG KONG', 'EL SALVADOR', 'ANGOLA', 'BERMUDA', 'MONTENEGRO',
       'IRAN', 'TUNISIA', 'NAMIBIA', 'NORTH ATLANTIC OCEAN', 'PORTUGAL',
       'SOUTH CHINA SEA', 'BANGLADESH', 'PALAU', 'WESTERN SAMOA',
       'PACIFIC OCEAN ', 'BRITISH ISLES', 'GRENADA', 'IRAQ', 'TURKEY',
       'SINGAPORE', 'NEW BRITAIN', 'SUDAN', 'JOHNSTON ISLAND',
       'SOUTH PACIFIC OCEAN', 'NEW GUINEA', 'RED SEA',
       'NORTH PACIFIC OCEAN', 'FEDERATED STATES OF MICRONESIA',
       'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES', 'MID ATLANTIC OCEAN',
       'PERSIAN GULF', 'RED SEA / INDIAN OCEAN', 'PACIFIC OCEAN',
       'NORTH SEA', 'NICARAGUA ', 'MALDIVE ISLANDS', 'AMERICAN SAMOA',
       'ANDAMAN / NICOBAR ISLANDAS', 'GABON', 'MAYOTTE',
       'NORTH ATLANTIC OCEAN ', 'THE BALKANS', 'SUDAN?', 'ARGENTINA',
       'MARTINIQUE', 'INDIAN OCEAN', 'GUATEMALA', 'NETHERLANDS ANTILLES',
       'NORTHERN MARIANA ISLANDS', 'IRAN / IRAQ', 'JAVA', ' PHILIPPINES',
       'NICARAGUA', 'CENTRAL PACIFIC', 'SOLOMON ISLANDS / VANUATU',
       'SOUTHWEST PACIFIC OCEAN', 'BAY OF BENGAL', 'MID-PACIFC OCEAN',
       'SOUTH ATLANTIC OCEAN', 'SLOVENIA', 'CURACAO', 'ICELAND',
       'ITALY / CROATIA', 'BARBADOS', 'MONACO', 'GUYANA', 'HAITI',
       'SAN DOMINGO', 'IRELAND', 'KUWAIT', 'YEMEN ', 'REUNION ISLAND',
       'FALKLAND ISLANDS', 'CRETE', 'CYPRUS', 'EGYPT ', 'WEST INDIES',
       'BURMA', 'LEBANON', 'PARAGUAY', 'BRITISH NEW GUINEA', 'CEYLON',
       'OCEAN', 'GEORGIA', 'SYRIA', 'TUVALU', 'INDIAN OCEAN?', 'GUINEA',
       'ANDAMAN ISLANDS', 'EQUATORIAL GUINEA / CAMEROON', 'COOK ISLANDS',
       'TOBAGO', 'PERU', 'AFRICA', 'ALGERIA', 'COAST OF AFRICA',
       'TASMAN SEA', 'GHANA', 'GREENLAND', 'MEDITERRANEAN SEA', 'SWEDEN',
       'ROATAN', 'BETWEEN PORTUGAL & INDIA', 'DJIBOUTI', 'BAHREIN',
       'KOREA', 'RED SEA?', 'ASIA?', 'CEYLON (SRI LANKA)'], dtype=object)

In [1005]:
# A dict with these incongs. I might share this with the class later on in case it's useful for them (if that's ok)
# fun fact I discovered: João da Nova, a Galician navigator 
#serving the Portuguese Empire (LET'S GO PORTUGAL), was the first person to sight Saint Helena. 🤓🤓🤓

countries_correct_names_dict = {
    'ST HELENA, BRITISH OVERSEAS TERRITORY': 'SAINT HELENA',
    'UNITED ARAB EMIRATES (UAE)':'UNITED ARAB EMIRATES',
    'AZORES': 'PORTUGAL',
    'NEVIS':'SAINT KITTS AND NEVIS',
    'DIEGO GARCIA':'BRITISH INDIAN OCEAN TERRITORY',
    'PALESTINIAN TERRITORIES': 'PALESTINE', #let's not get political here, interesting timing to clean this data though
    'GULF OF ADEN' : 'YEMEN',
    'ST. MAARTIN' : 'ST. MARTIN',
    'MEXICO ': 'MEXICO',
    ' TONGA' : 'TONGA',
    'OKINAWA':'JAPAN',
    'EGYPT / ISRAEL' : 'EGYPT',
    'SOUTH CHINA SEA':'CHINA',
    'FEDERATED STATES OF MICRONESIA' : 'MICRONESIA',
    'SUDAN?' : 'SUDAN', #"close to the wind-exposed side of an atollshaped reef off Sudan. " close enough, I'll take it
    'IRAN / IRAQ' : 'IRAN',
    'ITALY / CROATIA' : 'ITALY', #based on the PDF
    'WEST INDIES' : 'USA',
    'INDIAN OCEAN?': 'INDIA', #pdf
    'EQUATORIAL GUINEA / CAMEROON' : 'EQUATORIAL GUINEA',
    'CEYLON (SRI LANKA)' : 'SRI LANKA',
    'COAST OF AFRICA': 'SAINT THOMAS',
    'TASMAN SEA' : 'AUSTRALIA', 
    'ENGLAND' : 'UNITED KINGDOM',
    'SCOTLAND' : 'UNITED KINGDOM' 
}



#and now I replace these strange countries with the actual one:
sharks_q1['Country'] = sharks_q1['Country'].replace(countries_correct_names_dict)

In [1006]:
atlantic_ocean_country_rows = sharks_q1[sharks_q1["Country"]=="ATLANTIC OCEAN"]
atlantic_ocean_country_rows

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1007]:
# For atlantic ocean I had to check the other columns to get the real country,
# couldn't find much. but these two entries could be changed:
sharks_q1.loc[sharks_q1['Location'] == 'East of La Grande Island, North of Panama Canal', 'Country'] = 'PANAMA'
sharks_q1.loc[sharks_q1['Location'] == '360 miles north of Ascension Island', 'Country'] = 'ASCENSION ISLAND'

In [1008]:
# dropping the remaining "ATLANTIC OCEAN" in the countries. It's 15 entries and even though it sounds lazy,
# I'll have much more data to clean than to go into each PDF and check for the actual country
sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'ATLANTIC OCEAN'].index, inplace=True)

In [1009]:
#checking wth is it with country = "GULF OF ADEN"
gulf_of_aden = sharks_q1[sharks_q1["Country"] == "GULF OF ADEN"]
gulf_of_aden

#(ok, it was yemen based on the PDF)

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1010]:
#checking wth is it with country = "CARIBBEAN SEA"
caribbean_sea = sharks_q1[sharks_q1["Country"] == "CARIBBEAN SEA"]
caribbean_sea

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1011]:
# For Caribbean sea I had to check the other columns to get the real country,
# couldn't find much. but these entries could be changed:
sharks_q1.loc[sharks_q1['Location'] == 'Between St. Maarten & Anguilla', 'Country'] = 'ST. MARTIN'
sharks_q1.loc[sharks_q1['Location'] == 'Off Dominican Republic', 'Country'] = 'DOMINICAN REPUBLIC'
sharks_q1.loc[sharks_q1['Location'] == 'Between USA & Cuba', 'Country'] = 'USA'
sharks_q1.loc[sharks_q1['Location'] == 'Between Key West, Florida & Guantanamo Bay, Cuba', 'Country'] = 'USA'
sharks_q1.loc[sharks_q1['Location'] == 'Off Cristobal, 200 miles northeast of the entrance to the Panama Canal', 'Country'] = 'PANAMA'
sharks_q1.loc[sharks_q1['Location'] == '125 nm north of Aruba', 'Country'] = 'ARUBA'
sharks_q1.loc[sharks_q1['Location'] == "Between St. Bart's and Saba", 'Country'] = 'ST. BARTHELEMY'

In [1012]:
# dropping the remaining "CARIBBEAN SEA" in the countries.
sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'CARIBBEAN SEA'].index, inplace=True)

In [1013]:
# dropping the "NORTHERN ARABIAN SEA" in the countries. Reason> mid ocean not relevant fr my analysis
sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'NORTHERN ARABIAN SEA'].index, inplace=True)

In [1014]:
#checking wth is it with country = "NORTH ATLANTIC OCEAN"
northatln_ocean = sharks_q1[sharks_q1["Country"] == "NORTH ATLANTIC OCEAN"]
northatln_ocean

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1015]:
# For NORTH ATLANTIC OCEAN  I had to check the other columns to get the real country,
sharks_q1.loc[sharks_q1['Area'] == 'In the Gulf Stream', 'Country'] = 'USA'
sharks_q1.loc[sharks_q1['Area'] == 'South Carolina', 'Country'] = 'USA'
sharks_q1.loc[sharks_q1['Area'] == 'Georges Bank', 'Country'] = 'USA'
sharks_q1.loc[sharks_q1['Location'] == 'Between Bimini & Miami', 'Country'] = 'USA'

In [1016]:
# dropping the "NORTHERN ARABIAN SEA" in the countries. Reason> mid ocean not relevant fr my analysis
sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'NORTH ATLANTIC OCEAN'].index, inplace=True)

In [1033]:
#checking wth is it with country = "PACIFIC OCEAN"
pacific_ocean = sharks_q1[sharks_q1["Country"] == "PACIFIC OCEAN"]
pacific_ocean

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1034]:
# For PACIFIC OCEAN  I had to check the other columns to get the real country,
sharks_q1.loc[sharks_q1['Area'] == '180 miles southeast of Okinawa', 'Country'] = 'JAPAN'
sharks_q1.loc[sharks_q1['Area'] == 'Between Hawaii & Wake Island', 'Country'] = 'USA'
sharks_q1.loc[sharks_q1['Area'] == '1,000 miles east of Hawaii', 'Country'] = 'USA'
sharks_q1.loc[sharks_q1['Area'] == '330 to 350 miles east of Wake Island', 'Country'] = 'WAKE ISLAND'
sharks_q1.loc[sharks_q1['Location'] == 'In Los Angeles  Honolulu yacht race', 'Country'] = 'USA'
sharks_q1.loc[sharks_q1['Location'] == 'Off Central American coast at 8N.79W', 'Country'] = 'USA'
sharks_q1.loc[sharks_q1['Area'] == 'Near the Fiji Islands', 'Country'] = 'FIJI'
sharks_q1.loc[sharks_q1['Area'] == 'Northwest of Papua New Guinea', 'Country'] = 'PAPUA NEW GUINEA'
sharks_q1.loc[sharks_q1['Area'] == 'Between Hawaii and U.S.A', 'Country'] = 'PAPUA NEW GUINEA'
sharks_q1.loc[sharks_q1['Area'] == 'Off coast of Ecuador', 'Country'] = 'ECUADOR'

sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'PACIFIC OCEAN'].index, inplace=True)
sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'PACIFIC OCEAN '].index, inplace=True)

# AT THIS POINT I'M REALLY CONSIDERING WHETHER PEOPLE KNOW HOW TO READ COLUMN HEADERS WHEN FILLING OUT A FORM/REPORTING STUFF, AND AM ONLY IN THE BEGINNING :')

In [1035]:
#checking wth is it with country = "SOUTH PACIFIC OCEAN"
south_pacific_ocean = sharks_q1[sharks_q1["Country"] == "SOUTH PACIFIC OCEAN"]
south_pacific_ocean

sharks_q1.loc[sharks_q1['Case Number'] == '1965.06.00', 'Country'] = 'PAPUA NEW GUINEA'

sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'SOUTH PACIFIC OCEAN'].index, inplace=True)

In [1036]:
#checking wth is it with country = "RED SEA"
red_sea = sharks_q1[sharks_q1["Country"] == "RED SEA"]
red_sea

sharks_q1.loc[sharks_q1['Country'] == '1965.06.00', 'Country'] = 'PAPUA NEW GUINEA'

sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'RED SEA'].index, inplace=True) #it was in a gulf, adds no value to my analysis

In [1037]:
#checking wth is it with country = "NORTH PACIFIC OCEAN"
north_pacific_ocean = sharks_q1[sharks_q1["Country"] == "NORTH PACIFIC OCEAN"]
north_pacific_ocean

sharks_q1.loc[sharks_q1['Area'] == 'Wake Island (EnenKio)', 'Country'] = 'MICRONESIA'
sharks_q1.loc[sharks_q1['Area'] == '1000 miles west of Hawaii', 'Country'] = 'MICRONESIA'
sharks_q1.loc[sharks_q1['Location'] == 'Between Wake & Johnston Islands', 'Country'] = 'MICRONESIA'
sharks_q1.loc[sharks_q1['Area'] == 'Between Kwajalein Atoll & Johnston Island', 'Country'] = 'MICRONESIA'
sharks_q1.loc[sharks_q1['Location'] == 'Wake Island', 'Country'] = 'MICRONESIA'

sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'NORTH PACIFIC OCEAN'].index, inplace=True)
north_pacific_ocean

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1038]:
#checking wth is it with country = "MID ATLANTIC OCEAN"
mid_atlantic_ocean = sharks_q1[sharks_q1["Country"] == "MID ATLANTIC OCEAN"]
mid_atlantic_ocean

sharks_q1.loc[sharks_q1['Area'] == '1000 miles west of Hawaii', 'Country'] = 'MICRONESIA'
sharks_q1.loc[sharks_q1['Location'] == 'Off Bermuda', 'Country'] = 'BERMUDA'
sharks_q1.loc[sharks_q1['Area'] == '165 miles from Bermuda', 'Country'] = 'BERMUDA'
sharks_q1.loc[sharks_q1['Area'] == 'Between England & South Africa', 'Country'] = 'UNITED KINGDOM'
sharks_q1.loc[sharks_q1['Area'] == 'Bound from New York to London in ballast', 'Country'] = 'USA'
sharks_q1.loc[sharks_q1['Location'] == 'Venezuelan aircraft lost', 'Country'] = 'USA'


sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'MID ATLANTIC OCEAN'].index, inplace=True)
mid_atlantic_ocean

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1039]:
south_atlantic_ocean = sharks_q1[sharks_q1["Country"] == "SOUTH ATLANTIC OCEAN"]
south_atlantic_ocean

sharks_q1.loc[sharks_q1['Area'] == 'Off Libya', 'Country'] = 'LIBYA'
sharks_q1.loc[sharks_q1['Area'] == 'North of Pernambuco, Brazil', 'Country'] = 'BRAZIL'
sharks_q1.loc[sharks_q1['Area'] == 'South of the Equator', 'Country'] = 'ECUADOR'
sharks_q1.loc[sharks_q1['Location'] == 'Off Sierra Leone', 'Country'] = 'SIERRA LEONE'
sharks_q1.loc[sharks_q1['Area'] == 'Off Libya', 'Country'] = 'LIBYA'


sharks.drop(sharks_q1[sharks_q1['Country'] == 'SOUTH ATLANTIC OCEAN'].index, inplace=True)
south_atlantic_ocean

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1040]:
sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'PERSIAN GULF'].index, inplace=True)
sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'RED SEA / INDIAN OCEAN'].index, inplace=True)
sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'THE BALKANS'].index, inplace=True)

In [1041]:
indian_ocean = sharks_q1[sharks_q1["Country"] == "INDIAN OCEAN"]
indian_ocean

sharks_q1.loc[sharks_q1['Location'] == 'Between Straits of Malacca and Sri Lanka', 'Country'] = 'SRI LANKA'
sharks_q1.loc[sharks_q1['Location'] == 'Bound from Cape Town for St. Helena', 'Country'] = 'SOUTH AFRICA'
sharks_q1.loc[sharks_q1['Location'] == 'Between Straits of Malacca and Sri Lanka', 'Country'] = 'SRI LANKA'
sharks_q1.loc[sharks_q1['Area'] == 'West of Ceylon (Sri Lanka)', 'Country'] = 'SRI LANKA'
sharks_q1.loc[sharks_q1['Area'] == 'Between Noumea & Sydney', 'Country'] = 'AUSTRALIA'
sharks_q1.loc[sharks_q1['Area'] == 'Between Perth & Colombo', 'Country'] = 'AUSTRALIA'

sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'INDIAN OCEAN'].index, inplace=True)
indian_ocean

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1042]:
central_pacific = sharks_q1[sharks_q1["Country"] == "CENTRAL PACIFIC"]
central_pacific

sharks_q1.loc[sharks_q1['Location'] == '68 miles east of Wallis Island', 'Country'] = 'WALLIS'
central_pacific

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1043]:
sw_pac_ocean = sharks_q1[sharks_q1["Country"] == "SOUTHWEST PACIFIC OCEAN"]
sw_pac_ocean

sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'SOUTHWEST PACIFIC OCEAN'].index, inplace=True)
sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'BAY OF BENGAL'].index, inplace=True) #no country

sw_pac_ocean

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1044]:
africa_what_country = sharks_q1[sharks_q1["Country"] == "AFRICA"]
africa_what_country

sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'AFRICA'].index, inplace=True) #NOTHING FOUND ON THE PDF!!!! (no PDF found actually)

africa_what_country

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1045]:
medit_sea = sharks_q1[sharks_q1["Country"] == "MEDITERRANEAN SEA"]
medit_sea

sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'MEDITERRANEAN SEA'].index, inplace=True)
sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'BETWEEN PORTUGAL & INDIA'].index, inplace=True) #PDF doesnt give away the info, too bstract


medit_sea

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1046]:
red_sea = sharks_q1[sharks_q1["Country"] == "RED SEA?"]
red_sea

sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'RED SEA?'].index, inplace=True)


red_sea

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1047]:
is_it_asia = sharks_q1[sharks_q1["Country"] == "ASIA?"]
is_it_asia

sharks_q1.drop(sharks_q1[sharks_q1['Country'] == 'ASIA?'].index, inplace=True)


is_it_asia

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1048]:
#rechecking now:

sharks_q1["Country"].unique()

array(['USA', 'BRAZIL', 'AUSTRALIA', 'UNITED KINGDOM', 'COSTA RICA',
       'MALDIVES', 'SOUTH AFRICA', 'THAILAND', 'BAHAMAS', 'ECUADOR',
       'MALAYSIA', 'CUBA', 'SPAIN', 'JAPAN', 'EGYPT', 'SAINT HELENA',
       'MEXICO', 'REUNION', 'UNITED ARAB EMIRATES', 'PHILIPPINES',
       'INDONESIA', 'NEW CALEDONIA', 'CHINA', 'COLUMBIA', 'NEW ZEALAND',
       'FRENCH POLYNESIA', 'CAPE VERDE', 'FIJI', 'CAYMAN ISLANDS',
       'ARUBA', 'MOZAMBIQUE', 'PUERTO RICO', 'ITALY', 'MAURITIUS',
       'ST. MARTIN', 'PAPUA NEW GUINEA', 'KIRIBATI', 'ISRAEL', 'FRANCE',
       'BRITISH INDIAN OCEAN TERRITORY', 'JAMAICA', 'PALESTINE', 'GUAM',
       'SEYCHELLES', 'NIGERIA', 'TONGA', 'TRINIDAD & TOBAGO', 'CANADA',
       'CROATIA', 'SAUDI ARABIA', 'TAIWAN', 'DOMINICAN REPUBLIC', 'KENYA',
       'RUSSIA', 'TURKS & CAICOS', 'SAMOA', 'SOLOMON ISLANDS',
       'SOUTH KOREA', 'MALTA', 'VIETNAM', 'MADAGASCAR', 'PANAMA',
       'PORTUGAL', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'BELIZE',
       'GRAND CAYMAN', 'VANUATU', 'SRI LANKA', 'URUGUAY', 'VENEZUELA',
       'INDIA', 'TANZANIA', 'MARSHALL ISLANDS', 'SENEGAL', 'HONG KONG',
       'CHILE', 'SOMALIA', 'EL SALVADOR', 'BERMUDA', 'GREECE',
       'WESTERN SAMOA', 'BRITISH ISLES', 'MICRONESIA', 'PALAU', 'GRENADA',
       'IRAQ', 'TURKEY', 'SINGAPORE', 'NEW BRITAIN', 'NEW GUINEA',
       'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES', 'JOHNSTON ISLAND',
       'NORTH SEA', 'MALDIVE ISLANDS', 'AMERICAN SAMOA',
       'ANDAMAN / NICOBAR ISLANDAS', 'NORTH ATLANTIC OCEAN ', 'ARGENTINA',
       'IRAN', 'SIERRA LEONE', 'WALLIS', 'LIBYA', 'BARBADOS',
       'REUNION ISLAND', 'FALKLAND ISLANDS', 'NICARAGUA', 'EGYPT ',
       'YEMEN ', 'HAITI', 'BRITISH NEW GUINEA', 'HONDURAS', 'GUINEA'],
      dtype=object)

In [1053]:
#what values are there missing in the countries? Using nan:
missing_values_countries = sharks_q1["Country"].isna().sum()
missing_values_countries

0

In [1054]:
#note, the previous code returned 19471 NaN which make no sense. 
#Apparently the dataset ends in row 6303 and after that it's just a bunch of zeros and empty rows
#I'm removing these!

In [1055]:
whats_going_on_with_these_rows = sharks_q1.iloc[6240:6250]

whats_going_on_with_these_rows

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1056]:
#purpose of the above code was for me to check the change of data in row 6303 onwards.
#but because I've been deleting data, the index is all messed up. (jumped some values)
#so I'm resetting it:
sharks_q1 = sharks_q1.reset_index(drop=True)

In [1057]:
sharks_q1

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3343,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0,NaN,NaN,Unknown
3344,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN,NaN,Unknown
3345,ND.0051,Before 1957,0.0,Provoked,CUBA,Havana Province,Cojimar,"Shark fishing, knocked overboard",Sandrillio,M,50,"FATAL, hip bitten PROVOKED INCIDENT",Y,NaN,NaN,"F. Poli, pp.75, 81-83",ND-0051-Sandrillio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0051,ND.0051,49.0,NaN,NaN,Unknown
3346,ND.0026,Early 1930s,0.0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,16,FATAL,Y,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27.0,NaN,NaN,Unknown
3347,ND.0001,1845-1853,0.0,Unprovoked,SRI LANKA,Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

In [1058]:
whats_going_on_with_these_rows = sharks_q1.iloc[6240:6250]
whats_going_on_with_these_rows

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1059]:
#I will now delete all the rows that have no data (after index 6243), but 
#before messing up, making a copy just to be sure:

sharks_lets_delete_rows = sharks_q1.copy()
sharks_lets_delete_rows

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3343,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0,NaN,NaN,Unknown
3344,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN,NaN,Unknown
3345,ND.0051,Before 1957,0.0,Provoked,CUBA,Havana Province,Cojimar,"Shark fishing, knocked overboard",Sandrillio,M,50,"FATAL, hip bitten PROVOKED INCIDENT",Y,NaN,NaN,"F. Poli, pp.75, 81-83",ND-0051-Sandrillio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0051,ND.0051,49.0,NaN,NaN,Unknown
3346,ND.0026,Early 1930s,0.0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,16,FATAL,Y,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27.0,NaN,NaN,Unknown
3347,ND.0001,1845-1853,0.0,Unprovoked,SRI LANKA,Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

In [1060]:
sharks_lets_delete_rows.drop(sharks_lets_delete_rows.index[6244:], inplace=True)
sharks_lets_delete_rows

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3343,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0,NaN,NaN,Unknown
3344,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN,NaN,Unknown
3345,ND.0051,Before 1957,0.0,Provoked,CUBA,Havana Province,Cojimar,"Shark fishing, knocked overboard",Sandrillio,M,50,"FATAL, hip bitten PROVOKED INCIDENT",Y,NaN,NaN,"F. Poli, pp.75, 81-83",ND-0051-Sandrillio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0051,ND.0051,49.0,NaN,NaN,Unknown
3346,ND.0026,Early 1930s,0.0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,16,FATAL,Y,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27.0,NaN,NaN,Unknown
3347,ND.0001,1845-1853,0.0,Unprovoked,SRI LANKA,Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

In [1061]:
#ok, worked fine

In [1062]:
sharks_q1.drop(sharks_q1.index[6244:], inplace=True)
sharks_q1

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3343,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0,NaN,NaN,Unknown
3344,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN,NaN,Unknown
3345,ND.0051,Before 1957,0.0,Provoked,CUBA,Havana Province,Cojimar,"Shark fishing, knocked overboard",Sandrillio,M,50,"FATAL, hip bitten PROVOKED INCIDENT",Y,NaN,NaN,"F. Poli, pp.75, 81-83",ND-0051-Sandrillio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0051,ND.0051,49.0,NaN,NaN,Unknown
3346,ND.0026,Early 1930s,0.0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,16,FATAL,Y,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27.0,NaN,NaN,Unknown
3347,ND.0001,1845-1853,0.0,Unprovoked,SRI LANKA,Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

In [1142]:
sharks_q1["Country"].isna().sum()
#still have 50 na values

0

In [1143]:
sharks_q1[sharks_q1["Country"].isna()]

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1144]:
#replacing some of these:

In [1145]:
sharks_q1.loc[sharks_q1['Location'] == 'Between St. Kitts & Nevis', 'Country'] = 'SAINT KITTS AND NEVIS'
sharks_q1.loc[sharks_q1['Location'] == 'Florida Strait', 'Country'] = 'USA'
sharks_q1.loc[sharks_q1['Area'] == 'Between Timor & Darwin, Australia', 'Country'] = 'TIMOR'
sharks_q1.loc[sharks_q1['Area'] == 'Near the Andaman & Nicobar Islands', 'Country'] = 'ANDAMAN AND NICOBAR ISLANDS'
sharks_q1.loc[sharks_q1['Area'] == 'Between Comores & Madagascar', 'Country'] = 'MADAGASCAR'
sharks_q1.loc[sharks_q1['Area'] == 'Gulf of California', 'Country'] = 'USA'

In [1146]:
#I'll drop the reamining misisng values
sharks_q1.dropna(subset=['Country'], inplace=True)

In [1147]:
sharks_q1["Country"].isna().sum()

0

In [1148]:
sharks_q1[sharks_q1["Country"].isna()]

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1149]:
sharks_q1

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3343,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0,NaN,NaN,Unknown
3344,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN,NaN,Unknown
3345,ND.0051,Before 1957,0.0,Provoked,CUBA,Havana Province,Cojimar,"Shark fishing, knocked overboard",Sandrillio,M,50,"FATAL, hip bitten PROVOKED INCIDENT",Y,NaN,NaN,"F. Poli, pp.75, 81-83",ND-0051-Sandrillio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0051,ND.0051,49.0,NaN,NaN,Unknown
3346,ND.0026,Early 1930s,0.0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,16,FATAL,Y,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27.0,NaN,NaN,Unknown
3347,ND.0001,1845-1853,0.0,Unprovoked,SRI LANKA,Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

# I've got the first (almost) working dataframe: sharks_q1_countries_cleaned

## Cleaning "Age"

In [1150]:
#before anything, I'm creating a copy of the filtered countries df!

#sharks_q1_countries_cleaned = sharks_q1.copy() #and now that it's copied, I'm freezing this line of code not to overwite it!
sharks_q1_countries_cleaned = sharks_q1_countries_cleaned.reset_index(drop=True)
sharks_q1_countries_cleaned = sharks_q1_countries_cleaned.drop_duplicates(subset=['Case Number', 'Date', 'Country'], keep='first')
sharks_q1_countries_cleaned

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3343,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0,NaN,NaN,Unknown
3344,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN,NaN,Unknown
3345,ND.0051,Before 1957,0.0,Provoked,CUBA,Havana Province,Cojimar,"Shark fishing, knocked overboard",Sandrillio,M,50,"FATAL, hip bitten PROVOKED INCIDENT",Y,NaN,NaN,"F. Poli, pp.75, 81-83",ND-0051-Sandrillio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0051,ND.0051,49.0,NaN,NaN,Unknown
3346,ND.0026,Early 1930s,0.0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,16,FATAL,Y,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27.0,NaN,NaN,Unknown
3347,ND.0001,1845-1853,0.0,Unprovoked,SRI LANKA,Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

In [1151]:
#checking the nas first:
sharks_q1["Age"].isna().sum()
#that's a lot!

0

In [1152]:
sharks_q1[sharks_q1['Age'].isna()]

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1153]:
#but I can't seem to work this around with data from other columns so I might drop these rows:
sharks_q1.dropna(subset=['Age'], inplace=True)
sharks_q1["Age"].isna().sum()

0

In [1154]:
#Ok, now lets make sure the numbers in the column Age actually make sense
#using a try and except to do this:


def converting_the_ages_to_integer(age):
    try:
        return int(age) 
    except:
        return age

sharks_q1['Age'] = sharks_q1['Age'].apply(converting_the_ages_to_integer)

In [1155]:
#I now wanna get the values that are not integers: 
#found out that I can use lambda x: isinstance(x, int) to get the values that are indeed integers
#but using "~" in the beginning to contradict and get the opposite. I want them in a list to decide what to do:
ages_that_are_not_ints = sharks_q1.loc[~sharks_q1['Age'].apply(lambda x: isinstance(x, int)), 'Age'].tolist()
ages_that_are_not_ints

[]

In [1156]:
#other than "both 11" the rest makes no sense to me to be used in my analysis. I'll drop them
sharks_q1.loc[sharks_q1['Age'] == 'Both 11', 'Age'] = int(11)
sharks_q1 = sharks_q1[sharks_q1['Age'].apply(lambda x: isinstance(x, int))] #here saying that sharks_q1 is only the sharks_q1 where the instance is actually and Integer

In [1157]:
#I now wanna make sure that I've only got reasonable numbers, like no one is Dracula old 
#neither do I have negative age people
#I'll give it a chance people are between 0 and 100yo (stay home if you're that old and putting urself out there like a champ)

condition_age_is_reasonable = (sharks_q1['Age'] >= 0) & (sharks_q1['Age'] <= 100)
valid_age_rows = sharks_q1[condition_age_is_reasonable]
print(valid_age_rows.shape)
print(sharks_q1.shape)

(3348, 25)
(3348, 25)

In [1158]:
#the shapes coincide! that means that Age column respects the condition I set (0-100 yrs). Nice

#### Before I assume sharks_q1 is the final dataframe I'll be working with, I will remove the duplicates.
Duplicates to me will be rows where 
Case Number
Date
Country
have the exact same values and here I'll only store the top row.

In [1159]:
sharks_q1 = sharks_q1.drop_duplicates(subset=['Case Number', 'Date', 'Country'], keep='first')
sharks_q1.shape

#(actually just dropped one duplicate, but still)

(3348, 25)

# now: sharks_q1_countries_and_age_cleaned

In [1160]:
#before anything, I'm storing this as another new dataframe, ready to be used for Q1:

sharks_q1_countries_and_age_cleaned = sharks_q1.copy()# and freezing this code so I don't overwrite countries_and_age_cleaned
#resetting the index and removing the duplicates:
sharks_q1_countries_and_age_cleaned = sharks_q1_countries_and_age_cleaned.reset_index(drop=True)

sharks_q1_countries_and_age_cleaned

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3343,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0,NaN,NaN,Unknown
3344,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN,NaN,Unknown
3345,ND.0051,Before 1957,0.0,Provoked,CUBA,Havana Province,Cojimar,"Shark fishing, knocked overboard",Sandrillio,M,50,"FATAL, hip bitten PROVOKED INCIDENT",Y,NaN,NaN,"F. Poli, pp.75, 81-83",ND-0051-Sandrillio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0051,ND.0051,49.0,NaN,NaN,Unknown
3346,ND.0026,Early 1930s,0.0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,16,FATAL,Y,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27.0,NaN,NaN,Unknown
3347,ND.0001,1845-1853,0.0,Unprovoked,SRI LANKA,Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

In [1161]:
#exporting:
sharks_q1_countries_and_age_cleaned.to_csv('./data/Q1 attacks.csv', index=False)

## Cleaning "Fatal (Y/N)"

In [1162]:
"""
assumption - sharks_q1 will be my starting point to work on other dataframes as, even though I removed some 
entries that did not have information about countries but might have had information about other columns
that I could have used for other analysis, LESSON LEARNED:
before actually cleaning data in one specific column, start cleaning data that's transversal to the whole Dataframe,
in this example, I should have started by cleaning the empty rows for example. 
Now I will have to start over again from sharks by cleaning those rows. Oh welll.
"""

"\nassumption - sharks_q1 will be my starting point to work on other dataframes as, even though I removed some \nentries that did not have information about countries but might have had information about other columns\nthat I could have used for other analysis, LESSON LEARNED:\nbefore actually cleaning data in one specific column, start cleaning data that's transversal to the whole Dataframe,\nin this example, I should have started by cleaning the empty rows for example. \nNow I will have to start over again from sharks by cleaning those rows. Oh welll.\n"

In [1163]:
sharks_starting_point = sharks.iloc[:6302] #removing those excessive rows
sharks_starting_point = sharks_starting_point.drop_duplicates(subset=['Case Number', 'Date', 'Country'], keep='first')
sharks_starting_point

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,Unknown
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Unknown
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Unknown
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Unknown
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown
6302,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6304.0,NaN,NaN,Unknown

In [1164]:
#what entries do I actually have here?
#let me try to create a DT for question 2:
sharks_q2 = sharks_starting_point.copy()

unique_values_q2 = sharks_q2['Fatal (Y/N)'].unique()
print(unique_values_q2)

['N' 'Y' nan 'M' 'UNKNOWN' '2017' ' N' 'N ' 'y']

In [1165]:
#got some extra spacing that I will replace. Wait! Actually better than replacing,
#these strings will strip for me as if they was at tha club. Meaning "strip()" will delete those stupid spaces:

sharks_q2['Fatal (Y/N)'] = sharks_q2['Fatal (Y/N)'].str.strip()
unique_values_q2 = sharks_q2['Fatal (Y/N)'].unique()
print(unique_values_q2)

['N' 'Y' nan 'M' 'UNKNOWN' '2017' 'y']

In [1166]:
#also got som lower case y:
sharks_q2['Fatal (Y/N)'] = sharks_q2['Fatal (Y/N)'].str.upper()
unique_values_q2 = sharks_q2['Fatal (Y/N)'].unique()
print(unique_values_q2)

['N' 'Y' nan 'M' 'UNKNOWN' '2017']

In [1167]:
"""
now I "just" have to deal with 
4 nan 
2'M' 
3'UNKNOWN' 
1'2017'

"""

'\nnow I "just" have to deal with \n4 nan \n2\'M\' \n3\'UNKNOWN\' \n1\'2017\'\n\n'

In [1168]:
# 1 "2017"
sharks_q2_fatal_is_2017 = sharks_q2[sharks_q2['Fatal (Y/N)'] =="2017"]
sharks_q2_fatal_is_2017

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
786,2012.06.10,10-Jun-2012,2012.0,Provoked,ITALY,Sardinia,Muravera,Attempting to rescue an injured & beached shark,Giorgio Zara,M,57,Lower left leg injured PROVOKED ACCIDENT,2017,Morning,"Blue shark, 2.5m","D. Puddo, 6/11/2012",2012.06.10-Zara.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.06.10,2012.06.10,5517.0,NaN,NaN,Unknown

In [1169]:
#clearly not fatal. Let's change

#sharks_q2.loc[sharks_q2["Fatal (Y/N)"] == "2017", "Fatal (Y/N)"] = "N"
sharks_q2.loc[sharks_q2["Fatal (Y/N)"] == "2017", "Fatal (Y/N)"] = "N"

unique_values_q2 = sharks_q2['Fatal (Y/N)'].unique()
print(unique_values_q2)

['N' 'Y' nan 'M' 'UNKNOWN']

In [1170]:
#2. "M"

In [1171]:
sharks_q2_fatal_is_M = sharks_q2[sharks_q2["Fatal (Y/N)"]=="M"]
sharks_q2_fatal_is_M

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
285,2016.04.18.b,18-Apr-2016,2016.0,Provoked,FRENCH POLYNESIA,Tuamotos,Makemo Atoll,Spearfishing,Hoata Iotua,M,22,Laceration to knee by speared shark PROVOKED I...,M,Morning,"Grey reef shark, 2 m","TNTV News, 4/19/2016",2016.04.18.b-Iotua.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.04.18.b,2016.04.18.b,6018.0,NaN,NaN,Unknown

In [1172]:
#the PDF is not opening and the rest of the cols tell me nothin. I'm dropping this value

In [1173]:
sharks_q2 = sharks_q2.drop(sharks_q2[sharks_q2["Fatal (Y/N)"]=="M"].index)
unique_values_q2 = sharks_q2['Fatal (Y/N)'].unique()
print(unique_values_q2)

['N' 'Y' nan 'UNKNOWN']

In [1174]:
#3 Unknow
sharks_q2_fatal_unknown = sharks_q2[sharks_q2["Fatal (Y/N)"] == "UNKNOWN"]
sharks_q2_fatal_unknown

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
624,2013.09.08,08-Sep-2013,2013.0,Unprovoked,USA,South Carolina,"St. Helena Island, Beaufort County",NaN,female,F,NaN,No details,UNKNOWN,NaN,NaN,"WIS-TV, 9/9/2013",2013.09.08-St-Helena.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.09.08,2013.09.08,5679.0,NaN,NaN,Unknown
1270,2008.04.20.a,20-Apr-2008,2008.0,Unprovoked,AUSTRALIA,New South Wales,Crescent Head,NaN,Jamie Adlington,M,NaN,NaN,UNKNOWN,NaN,"Tiger shark, 2.3m","T. Peake, GSAF",2008.04.20.a-Adlington.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.04.20.a,2008.04.20.a,5033.0,NaN,NaN,Unknown
2250,1997.06.07,07-Jun-1997,1997.0,Unprovoked,BRAZIL,Rio de Janeiro,"Copacabana, Rio de Janeiro",Bathing,José Luiz Lipiani,M,NaN,NaN,UNKNOWN,NaN,NaN,"Globo, 6/9/1997",1997.06.07-NV-Lipiani.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1997.06.07,1997.06.07,4053.0,NaN,NaN,Unknown
2260,1997.02.21,21-Feb-1997,1997.0,Unprovoked,USA,Hawaii,"Sunset Beach, O'ahu",NaN,Gersome Perreno,M,NaN,No details,UNKNOWN,NaN,NaN,G. Balazs,1997.02.21-NV-Perreno.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1997.02.21,1997.02.21,4043.0,NaN,NaN,Unknown
2267,1996.12.29,29-Dec-1996,1996.0,Unprovoked,AUSTRALIA,Queensland,Coolum Beach,Surfing,Blair Hall,M,18,NaN,UNKNOWN,18h00,NaN,"The Advertiser, 12/30/1996, p.3",1996.12.29-BlairHall.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1996.12.29,1996.12.29,4036.0,NaN,NaN,Evening
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6167,1617.00.00.R,Reported 1617,1617.0,Unprovoked,INDIA,West Bengal,Ganges Delta,NaN,Indian people,NaN,NaN,NaN,UNKNOWN,NaN,NaN,"H. Edwards, p.31, citing Samuel Purchas",1617.00.00-Purchas.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1617.00.00.R,1617.00.00.R,136.0,NaN,NaN,Unknown
6169,1595.00.00,1595,1595.0,Unprovoked,INDIA,Kerala,River Cochin,Ship lay at anchor & man was working on its ru...,male,M,NaN,"Leg severed mid-thigh, hand severed, arm above...",UNKNOWN,NaN,NaN,The Voyage of John Huyghen van Linschoten,1595.00.00-Cochin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1595.00.00,1595.00.00,134.0,NaN,NaN,Unknown
6171,1555.00.00,1555,1555.0,Unprovoked,NaN,NaN,NaN,Swimming,male,M,NaN,NaN,UNKNOWN,NaN,NaN,Olaus Magnus,1555.00.00 - Olaus Magnus.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1555.00.00,1555.00.00,132.0,NaN,NaN,Unknown
6172,1554.00.00,Ca. 1554,1554.0,Unprovoked,FRANCE,Nice & Marseilles,NaN,NaN,males (wearing armor),M,NaN,NaN,UNKNOWN,NaN,Possibly white sharks,G. Rondelet,1554.00.00-Rondelet.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1554.00.00,1554.00.00,131.0,NaN,NaN,Unknown
6277,ND.0025,Before 1927,0.0,Unprovoked,AUSTRALIA,New South Wales,"Spectacle Island, Port Jackson",NaN,"male, the Sergeant of Marines",M,NaN,NaN,UNKNOWN,NaN,NaN,H. Capper,ND-0025-Sgt-SpectacleIsland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0025,ND.0025,26.0,NaN,NaN,Unknown

In [1175]:
#I actually wanna get the unknowns in a list from the injuries to better assert watcha do:
list_fatal_unknown_injuries = sharks_q2.loc[sharks_q2["Fatal (Y/N)"] == "UNKNOWN", "Injury"].tolist()

list_fatal_unknown_injuries

['No details',
 nan,
 nan,
 'No details',
 nan,
 'No details',
 'No details',
 'No details',
 'No details',
 'No details',
 'No details',
 'No details',
 nan,
 'No details, "recovering in Darwin Hospital"',
 'No details',
 'No details',
 'No details',
 'No details',
 'No details',
 'No details',
 'No details',
 'No details',
 nan,
 'No details',
 nan,
 'No details',
 'No details',
 'No details',
 nan,
 'No details, listed as PROVOKED INCIDENT',
 'No details',
 'Involved a speared shark but no other details PROVOKED INCIDENT',
 nan,
 'Details unknown, possibly a PROVOKED INCIDENT',
 nan,
 nan,
 nan,
 'Man landed at Cape Levêque lighthouse in critical condition after being bitten by a shark. Not known if he survived.',
 'No details',
 'No details',
 'No details',
 'No details',
 nan,
 'Unprovoked, but circumstances unknown',
 'No details',
 'No details',
 nan,
 'No details',
 'No details',
 'No details',
 'Shark involvement not confirmed',
 'No details',
 'Calf removed, not known if he survived ',
 'No injury',
 'No details',
 'No injury',
 '"Painfully injured" but no details',
 'No details',
 'No details',
 'No details',
 'Severe bite to thigh. Not known if he survived',
 'No details, it was the year the first settlers came ashore in Holdfast Bay, Port Pirie',
 nan,
 nan,
 nan,
 nan,
 'Leg severed mid-thigh, hand severed, arm above elbow and part of buttocks. Not known if he survived',
 nan,
 nan,
 nan]

In [1176]:
#ok, so other than the Nan, I'll delete the UNKNOWNs. I could keep them, but I prefer to
#be straight to the point in my analysis. In my opinion, presenting a "I don't if they survived"
#will not add much to what I wanna say.
#dropping these.

sharks_q2 = sharks_q2.drop(sharks_q2[sharks_q2["Fatal (Y/N)"] == "UNKNOWN"].index)
unique_values_q2 = sharks_q2['Fatal (Y/N)'].unique()
print(unique_values_q2)

['N' 'Y' nan]

In [1177]:
sharks_q2_isna = sharks_q2[sharks_q2["Fatal (Y/N)"].isna()]
sharks_q2_isna

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0,NaN,NaN,Unknown
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01,6227.0,NaN,NaN,Unknown
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0,NaN,NaN,Afternoon
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0,NaN,NaN,Unknown
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b,6205.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6157,1733.00.00,1733,1733.0,Invalid,ICELAND,Bardestrand,Talkknefiord,NaN,NaN,NaN,NaN,"Partial hominid remains recovered from shark, ...",NaN,NaN,Shark involvement prior to death unconfirmed,E. Olafsen,1733.00.00-Iceland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1733.00.00,1733.00.00,146.0,NaN,NaN,Unknown
6158,1723.00.00,1723,1723.0,Unprovoked,ROATAN,NaN,NaN,NaN,Philip Ashton,M,NaN,Struck on thigh,NaN,NaN,NaN,"C.Moore, GSAF",1730.00.00-Ashton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1723.00.00,1723.00.00,145.0,NaN,NaN,Unknown
6164,1642.00.00.b,Late 1600s Reported 1728,1642.0,Invalid,GUINEA,NaN,NaN,Went overboard,crew member of the Nieuwstadt,M,NaN,FATAL,NaN,NaN,Questionable,"History of the Pyrates, by D. Defoe, Vol. 2, p.28",1642.00.00.b-Nieuwstadt.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1642.00.00.b,1642.00.00.b,139.0,NaN,NaN,Unknown
6232,ND.0081,"No date, Before 1963",0.0,Invalid,USA,Hawaii,"Portlock, Oahu",Diving,Val Valentine,M,NaN,A 4.3 m [14'] shark made threat display. No in...,NaN,NaN,Invalid,B. Sojka & D. Lloyd,ND-0081-Valentine.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0081,ND.0081,71.0,NaN,NaN,Unknown
6302,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6304.0,NaN,NaN,Unknown

In [1178]:
#a gazillion of Na where the injuries suggest the person died. 
#I'm tackling this via key words and RegEx:


fatal_keywords = r"(death|drowned|died|post mortem|drowning|fatal)"
 #I gotta start somewhere and after taking a quick
#look at the words in the comments on the injuries box, I'm gonna go agead with these as the catchers for casualties


#totally checked this online, not gonna lie:
fatal_rows = sharks_q2['Injury'].str.contains(
    fatal_keywords, case=False, na=False, regex=True
) & ~sharks_q2['Injury'].str.contains(
    r"\b(?:non-fatal|not[- ]?fatal)\b", case=False, na=False, regex=True
)


"""
r" here I'm initiating the Regex telling Python not to make a fuss out of the backlashes treating them as actual strings
\b this is a word boundary anchor. It asserts that the position is at a word boundary
(?:non-fatal|not[- ]?fatal): This is a non-capturing group (?:...) that contains an alternation (A|B) of different options.

non-fatal: This is a literal match for the word "non-fatal."

not[- ]?fatal: This part is more complex:

not: It's a literal match for the word "not."
[- ]?: This part matches a hyphen - or a space character , and the ? makes it optional. So, this part allows for variations like "not-fatal" or "not fatal."
\b: This is another word boundary anchor, ensuring that the matched word is a whole word.


"""


# Update "Fatal (Y/N)" for rows that meet the criteria to "Y"
sharks_q2.loc[fatal_rows, 'Fatal (Y/N)'] = 'Y'

C:\Users\mocid\AppData\Local\Temp\ipykernel_24516\2539310510.py:11: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  fatal_rows = sharks_q2['Injury'].str.contains(

In [1179]:
sharks_q2_isna = sharks_q2[sharks_q2["Fatal (Y/N)"].isna()]
sharks_q2_isna
#went from 537 NaN to 359  cause the difference 168 were actual casualties

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0,NaN,NaN,Unknown
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0,NaN,NaN,Afternoon
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b,6205.0,NaN,NaN,Unknown
107,2017.07.29.c,29-Jul-2017,2017.0,Invalid,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Johnny Simatacolos,M,10,Abrasions and cuts to sole of foot,NaN,15h00,A small shark,"C. Creswell, GSAF",2017.07.29.c-Simatacolos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.29.c,2017.07.29.c,6196.0,NaN,NaN,Afternoon
115,2017.07.20.c,20-Jul-2017,2017.0,Invalid,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Ellie Rogier,F,8,Foot injured,NaN,NaN,Shark involvement not confirmed,"C. Creswell, GSAF",2017.07.20.c-Rogier.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.20.c,2017.07.20.c,6188.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6126,1805.09.00,Sep-1805,1805.0,Invalid,USA,New York,"Sag Harbor, Suffolk County",NaN,NaN,M,NaN,human remains (male) found in sharks gut,NaN,NaN,Shark involvement prior to death unconfirmed,S.L. Mitchill (1814),1805.09.00-NY.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1805.09.00,1805.09.00,177.0,NaN,NaN,Unknown
6147,1767.00.00,1767,1767.0,Invalid,FRANCE,Côte d'Azur,St. Tropez,Bathing,Samuel Matthews,M,NaN,Lacerations to arm & leg,NaN,NaN,Description of shark does not ring true,NaN,1767.00.00-Matthews.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1767.00.00,1767.00.00,156.0,NaN,NaN,Unknown
6158,1723.00.00,1723,1723.0,Unprovoked,ROATAN,NaN,NaN,NaN,Philip Ashton,M,NaN,Struck on thigh,NaN,NaN,NaN,"C.Moore, GSAF",1730.00.00-Ashton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1723.00.00,1723.00.00,145.0,NaN,NaN,Unknown
6232,ND.0081,"No date, Before 1963",0.0,Invalid,USA,Hawaii,"Portlock, Oahu",Diving,Val Valentine,M,NaN,A 4.3 m [14'] shark made threat display. No in...,NaN,NaN,Invalid,B. Sojka & D. Lloyd,ND-0081-Valentine.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0081,ND.0081,71.0,NaN,NaN,Unknown
6302,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6304.0,NaN,NaN,Unknown

In [1180]:
#I'm dropping the remaining values

In [1181]:
sharks_q2.dropna(subset=["Fatal (Y/N)"], inplace=True)
unique_values_q2 = sharks_q2['Fatal (Y/N)'].unique()
print(unique_values_q2)

['N' 'Y']

In [1182]:
sharks_q2

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,Unknown
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,Unknown
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Unknown
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Unknown
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Unknown
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

In [1183]:
#so now I have a fully filled in column for fatality based on some keywords from the injuries column. I concede there's 
#not a 100% close to reality ratio in case there are some other strings representing death but I'm happy about what I've got

# now: sharks_q2_fatalities_cleaned

## Cleaning "Time"

In [1184]:
#ok, before aything else let's create a new DF with the cleaned fatalities, just in case it's gon be useful:

sharks_q2_fatalities_cleaned = sharks_q2.copy() #and freezing this code so I don't overwrite countries_and_age_cleaned
#resetting the index and removing the duplicates:
sharks_q2_fatalities_cleaned = sharks_q2_fatalities_cleaned.reset_index(drop=True)
sharks_q2_fatalities_cleaned = sharks_q2_fatalities_cleaned.drop_duplicates(subset=['Case Number', 'Date', 'Country'], keep='first')
sharks_q2_fatalities_cleaned

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,Unknown
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5840,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,Unknown
5841,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Unknown
5842,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Unknown
5843,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Unknown
5844,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

In [1185]:
#let's check the unique values, see how many Na we have and also non-time:

sharks_q2_time = sharks_q2["Time"].unique
print(sharks_q2_time)

<bound method Series.unique of 0               18h00
1       14h00  -15h00
2               07h45
3                 NaN
4                 NaN
            ...
6297              NaN
6298              NaN
6299              NaN
6300              NaN
6301              NaN
Name: Time, Length: 5845, dtype: object>

In [1186]:
"""
I will define different "categories" for the time:
(reference: https://www.britannica.com/dictionary/eb/qa/parts-of-the-day-early-morning-late-morning-etc)

Morning     5 am to 12 pm (noon)
Afternoon     12 pm to 5 pm
Evening     5 pm to 9 pm
Night         9 pm to 4 am

"""

'\nI will define different "categories" for the time:\n(reference: https://www.britannica.com/dictionary/eb/qa/parts-of-the-day-early-morning-late-morning-etc)\n\nMorning     5 am to 12 pm (noon)\nAfternoon     12 pm to 5 pm\nEvening     5 pm to 9 pm\nNight         9 pm to 4 am\n\n'

In [1187]:
#first off I'll deal with the data that's got an entry in the proper form "[Hour]h[minute]". 
#I'm actually creating a new column to categorize these times:

import re
#importing regular exprssns

time_categories = ["Morning", "Afternoon", "Evening", "Night"]
time_categories_intervals = [5, 12, 17, 21, 24] 

#as we've seen in class, to apply a function over a column we need to use the apply method.
#but first I'll create the function itself:

# Function to categorize the time intervals. Once again - had to ask for help online as Regex and I are not friends yet.
def categorize_the_time(time_str):
    """
categorizing the time into the 4 different categories I've defined ("Morning", "Afternoon", "Evening", "Night").
I realized lots of entries are done in the format HHhMM so I'm targeting these entries by capturing 2 groups (hour and minute)

r'(\d{1,2})h(\d{2})
is precisely tackling these 2 groups. 
\d - to match any numeric digit (0-9)
{1,2} - means the numbers can vary between on (imagine 9am) and 2 (imagine 11am)
h - literally people wrote "h" in the time entry
(\d{2}) - in the second group there are always gonna be 2 digits, even if it's 8h02 the 2 is actually "02"


"""    
    
    # Extract hours and minutes using regular expressions
    match = re.match(r'(\d{1,2})h(\d{2})', time_str)    
    if match:
        hour = int(match.group(1))
        minute = int(match.group(2))
        # Convert to a single hour value (0-23)
        hour_value = hour + minute / 60

        # Categorize based on time ranges
        if 5 <= hour_value < 12:
            return "Morning"
        elif 12 <= hour_value < 17:
            return "Afternoon"
        elif 17 <= hour_value < 21:
            return "Evening"
        else:
            return "Night"
    else:
        return "Unknown"

# Create a new column 'Time of Day' based on 'Time' column
#IGNORE THIS CODE: sharks['Time of Day'] = sharks['Time'].apply(categorize_the_time)
sharks_q2['Time of Day'] = sharks_q2['Time'].apply(lambda time_str: categorize_the_time(str(time_str))) 
#I was getting an error with the code above (the IGNORE one) as I was not casting the newly created col into a string.

In [1188]:
sharks_q2

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,Unknown
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,Unknown
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Unknown
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Unknown
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Unknown
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

In [1189]:
#cool now I've got my new column but I prefere if it was next to the OG column Time:
columns_q2 = list(sharks_q2.columns.values)
print(columns_q2)

['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location', 'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time', 'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href', 'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22', 'Unnamed: 23', 'Time of Day']

In [1190]:
columns_q2 = ['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location', 'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time', 'Time of Day', 'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href', 'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22', 'Unnamed: 23']
print(columns_q2)

['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location', 'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time', 'Time of Day', 'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href', 'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22', 'Unnamed: 23']

In [1191]:
sharks_q2 = sharks_q2[columns_q2]
sharks_q2.sample(30) #doing this to check that the function for the new column worked

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Time of Day,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
2419,1994.10.05,05-Oct-1994,1994.0,Unprovoked,USA,Florida,"Indialantic, Brevard County",Surfing,Scott Dulmage,M,16,Foot bitten,N,12h00,Afternoon,NaN,"Orlando Sentinel, 10/5/1994, p.B3",1994.10.05-ScottDulmage.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1994.10.05,1994.10.05,3884.0,NaN,NaN
310,2016.02.02,02-Feb-2016,2016.0,Unprovoked,BRAZIL,Balneário Camboriú,Estaleirinho beach,Swimming,Rafael Hermes Thomas,M,41,Lacerations to scalp,N,NaN,Unknown,Sandtiger shark,"Globo, 2/3/2016",2016.02.02-Thomas.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.02.02,2016.02.02,5993.0,NaN,NaN
4235,1956.08.20,20-Aug-1956,1956.0,Unprovoked,PAPUA NEW GUINEA,Central Province,"Paga Point, Port Moresby",Fishing,native,M,NaN,"Leg bitten, but survived",N,NaN,Unknown,NaN,"V.M. Coppleson (1958), pp.49 & 264; A.M. Rapso...",1956.08.20-native.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1956.08.20,1956.08.20,2068.0,NaN,NaN
4780,1940.00.00.b,1940,1940.0,Invalid,SOUTH AFRICA,KwaZulu-Natal,Winkelspruit,NaN,Indian female,F,NaN,FATAL,Y,NaN,Unknown,Questionable incident,"V.M. Coppleson (1958), p.247; SAF Case #161. U...",1940.00.00.b-IndianFemale.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1940.00.00.b,1940.00.00.b,1523.0,NaN,NaN
1149,2009.03.16.R,Reported 16-Mar-2009,2009.0,Provoked,AUSTRALIA,Western Australia,"The Natural Jetty, Rottnest Island",Wading,male,M,21,Thigh bitten when he trod on the shark PROVOKE...,N,NaN,Unknown,"Wobbegong shark, 60cm","The West, 3/16/2009",2009.03.16.R-Rottnest-Island.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2009.03.16.R,2009.03.16.R,5154.0,NaN,NaN
5105,1928.04.14.R,Reported 14-Apr-1928,1928.0,Unprovoked,AUSTRALIA,Queensland,"Barrow Point, 100 miles north of Cooktown, Que...",Fishing,a Murray Islander,M,NaN,Severe lacerations to arm,N,NaN,Unknown,Tiger shark,"The Western Champion, 4/14/1928",1928.04.14.R-BarrowPoint.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1928.04.14.R,1928.04.14.R,1198.0,NaN,NaN
3013,1981.09.03.a,03-Sep-1981,1981.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Surfing,Douglas Christie,M,24,Laceration to foot,N,Morning,Unknown,NaN,"St Petersburg Times, 9/5/1981",1981.09.03.a-Christie.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1981.09.03.a,1981.09.03.a,3290.0,NaN,NaN
6145,1776.00.00.b,1776,1776.0,Boat,GREENLAND,NaN,NaN,NaN,Occupants of skin boats,NaN,NaN,FATAL,Y,NaN,Unknown,White sharks,T. Pennant,1776.00.00-Greenland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1776.00.00.b,1776.00.00.b,158.0,NaN,NaN
1429,2006.09.18.R,Reported 18-Sep-2006,2006.0,Provoked,USA,Florida,"Off Key Largo, Monroe County",Diving / Kissing the shark,Dave Marcel,M,NaN,Lacerations to upper lip PROVOKED INCIDENT,N,NaN,Unknown,Nurse shark,"CBS-4, 9/18/2006",2006.09.18.R-DaveMarcel.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.09.18.R,2006.09.18.R,4874.0,NaN,NaN
4686,1943.00.00.d,1943,1943.0,Unprovoked,IRAQ,NaN,River Tigris,Swimming,Syed Khaleeulla,M,22,"Right arm severed, left foot bitten",N,NaN,Unknown,NaN,"Times of India, 8/19/2001",1943.00.00.d-Khaleeula.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1943.00.00.d,1943.00.00.d,1617.0,NaN,NaN
5127,1927.05.09.R,Reported 09-May 1927,1927.0,Unprovoked,AUSTRALIA,Queensland,Off Cairns,Walking,"Quassa, a Torres Strait Islander",M,NaN,FATAL,Y,NaN,Unknown,NaN,"Brisbane Courier, 5/10/1927; V.M. Coppleson (1...",1927.05.09.R-Quassa.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.05.09.R,1927.05.09.R,1176.0,NaN,NaN
1765,2003.06.24.c,24-Jun-2003,2003.0,Unprovoked,BRAZIL,Pernambuco,"Piedade, Recife",NaN,Moses Nunes de Albuquerque Junior,M,NaN,FATAL,Y,NaN,Unknown,NaN,"JCOnline, 6/23/2012",2003.06.24.c-MosesAlbuquerque.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.06.24.c,2003.06.24.c,4538.0,NaN,NaN
2181,1998.06.28.a,28-Jun-1998,1998.0,Unprovoked,AUSTRALIA,South Australia,South Neptune Island,Free diving for abalone,Doug Chesser,M,26,"FATAL, left thigh and lower leg severely injur...",Y,14h00,Afternoon,Thought to involve a 5.5 m white shark named Kong,R.W. Byard,1998.06.28-Chesser.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1998.06.28.a,1998.06.28.a,4122.0,NaN,NaN
6162,1700.00.00.b,1700s,1700.0,Unprovoked,FRANCE,Côte d'Azur,Antibes,Bathing,seaman,M,NaN,Leg severed,N,NaN,Unknown,White shark,"A. De Maddalena, citing Cazeils (1998)",1700.00.00.b-Antibes.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1700.00.00.b,1700.00.00.b,141.0,NaN,NaN
5125,1927.07.03,03-Jul-1927,1927.0,Boating,AUSTRALIA,New South Wales,Bellambi Reef,NaN,"14' boat, occupants: 2 men",NaN,NaN,"No injury to occupants, boat was bumped & lift...",N,NaN,Unknown,NaN,G.P. Whitley; V.M. Coppleson (1933); Note: V.M...,1927.07.03-Bellambi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.07.03,1927.07.03,1178.0,NaN,NaN
1489,2006.04.11,11-Apr-2006,2006.0,Unprovoked,AUSTRALIA,New South Wales,Newcastle Beach,Surfing,Luke Cook,M,15,Minor laceration to left foot,N,13h30,Afternoon,"Bronze whaler shark, a juvenile","Daily Telegraph, 4/12/2006",2006.04.11-Cook.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.04.11,2006.04.11,4814.0,NaN,NaN
5238,1921.11.27.a,27-Nov-1921,1921.0,Unprovoked,AUSTRALIA,Queensland,"Gays Corner, Bulimba Reach of Brisbane River","Wading to dinghy, carrying his son",Herbert Jack,M,40,"Right hip, buttock, elbow, arm & wrist bitten",N,Morning,Unknown,NaN,V.M. Coppleson.Q3. (1933); V.M. Coppleson (195...,1921.11.27.a-b-Jack.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1921.11.27.a,1921.11.27.a,1065.0,NaN,NaN
4543,1948.08.03,03-Aug-1948,1948.0,Unprovoked,IRAN,Shatt-al-Arab River,Bashamir,Swimming,Ismail,M,15,"Quadriceps lacerated, femur exposed",N,NaN,Unknown,NaN,"A. Anderson, M.D. / Lt. Col. R.S. Hunt, Royal ...",1948.08.03-Ismail.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1948.08.03,1948.08.03,1760.0,NaN,NaN
1647,2004.08.03,03-Aug-2004,2004.0,Unprovoked,AUSTRALIA,New South Wales,Byron Bay,Spearfishing,male,M,30,Minor puncture wounds to leg,N,14h00,Afternoon,NaN,"T. Peake, GSAF",2004.08.03-ByronBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2004.08.03,2004.08.03,4656.0,NaN,NaN
1895,2001.10.02,02-Oct-2001,2001.0,Unprovoked,AUSTRALIA,Queensland,200 miles offshore,Snorkeling,Katherine Jones,F,20,Lacerations to right forearm & shoulder injured,N,13h00,Afternoon,Bronze whaler shark?,K. Jones,2001.10.02-Katherine-Jones.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2001.10.02,2001.10.02,4408.0,NaN,NaN
458,2015.01.16,16-Jan-2015,2015.0,Unprovoked,AUSTRALIA,New South Wales,"Mollymook Beach, Bannister Head",Filming,Sam Smith,M,17,Bitten on hand & wrist,N,NaN,Unknown,1.5 m shark,"Milton-Ulladulla Times, 1/16/2015",2015.01.16-Smith.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.01.16,2015.01.16,5845.0,NaN,NaN
608,2013.10.26.a,26-Oct-2013,2013.0,Unprovoked,AUSTRALIA,Western Australia,"Little Island, near Hillarys",Diving for crayfish,Todd Robinson,M,NaN,"No injury, swim fin shredded",N,10h55,Morning,Reported to involve a 4 m white shark,"Sky News, 10/26/2013",2013.10.26.a-Robinson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.10.26.a,2013.10.26.a,5695.0,NaN,NaN
2915,1983.11.21,21-Nov-1983,1983.0,Sea Disaster,PHILIPPINES,Central Philippines,NaN,Ferry boat sank,Arturo Garces,M,NaN,Left foot nipped,N,NaN,Unknown,.5 m shark,"Montreal Gazette, 11/28/1983",1983.11.21-FerryDisaster.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1983.11.21,1983.11.21,3388.0,NaN,NaN
4080,1959.07.28,28-Jul-1959,1959.0,Unprovoked,USA,California,"Alligator Head, La Jolla, San Diego County",Spearfishing (but on surface),Verne S. Fleet,M,25,"14 punctures on right thigh, swim trunks torn",N,19h30,Evening,"Hammerhead shark, 1.8 m [6'] S. zygena identif...","D. Miller & R. Collier; R. Collier, pp.24-25; ...",1959.07.28-Fleet_Collier.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1959.07.28,1959.07.28,2223.0,NaN,NaN
5283,1917.11.00,Nov-1917,1917.0,Unprovoked,MOZAMBIQUE,Maputo Province,Off Inhaca Island,Wreck of the tug Magellan,a South African sailor,M,NaN,FATAL,Y,Night,Unknown,NaN,C.J. McGuinness,1917.11.00-Magellan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1917.11.00,1917.11.00,1020.0,NaN,NaN
632,2013.08.31.a,31-Aug-2013,2013.0,Unprovoked,USA,California,"Butterfly Beach, Montecito, Santa Barbara County",Swimming,Nick Kennedy,M,NaN,Foot bitten,N,23h00,Night,Salmon shark,R. Collier,2013.08.31.a-Kennedy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.08.31.a,2013.08.31.a,5671.0,NaN,NaN
1252,2008.06.01.b,01-Jun-2008,2008.0,Unprovoked,USA,South Carolina,Cherry Grove,Body surfing,Madi Taff,F,15,Foot bitten,N,18h30,Evening,5' shark,"C. Creswell, GSAF",2008.06.01.b-Taff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.06.01.b,2008.06.01.b,5051.0,NaN,NaN
6173,1543.00.00,Ca. 1543,1543.0,Unprovoked,VENEZUELA,Magarita or Cubagua Islands,NaN,Pearl diving,Indian slave,M,NaN,FATAL,Y,NaN,Unknown,NaN,J. Castro,1543.00.00.R-LasCasas.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1543.00.00,1543.00.00,130.0,NaN,NaN
1742,2003.09.14.c,14-Sep-2003,2003.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Jason Williams,M,30,Left foot: lacerations on heel and sole,N,16h14,Afternoon,3' shark,"S. Petersohn, GSAF",2003.09.14.c-JasonWilliams.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.09.14.c,2003.09.14.c,4561.0,NaN,NaN
1461,2006.07.09.b,09-Jul-2006,2006.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Wading,male,M,40,Dorsum of left foot bitten,N,17h00,Evening,NaN,"S. Petersohn, GSAF",2006.07.09.b-NewSmyrnaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.07.09.b,2006.07.09.b,4842.0,NaN,NaN

In [1192]:
"""
1. NaN (/Unknown)
2. Strange sh*t introduced
"""

#1 NaN
nan_time_of_day = sharks_q2[sharks_q2["Time"].isna()]
nan_time_of_day

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Time of Day,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,Unknown,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,Unknown,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris,M,NaN,"No injury, board bitten",N,NaN,Unknown,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.b,2018.06.03.b,6298.0,NaN,NaN
7,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,Unknown,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN
11,2018.05.21,21-May-2018,2018.0,Unprovoked,USA,South Carolina,"Isle of Palms, Charleston County",Boogie boarding,Trey de Boer,M,10,Injuries to lower right leg and foot,N,NaN,Unknown,NaN,"C. Creswell, GSAF",2018.05.21-deBoer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.21,2018.05.21,6292.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,Unknown,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,Unknown,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,Unknown,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,Unknown,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,Unknown,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [1193]:
#as Im looking at other columns, I cant seem to find relevant info to fill the NaN in. I'm dropping them.
sharks_q2 = sharks_q2.drop(sharks_q2[sharks_q2['Time'].isna()].index)
sharks_q2.shape

(2819, 25)

In [1194]:
#2. Strange sh*t introduced
sharks_q2_time_day_unknown = sharks_q2[sharks_q2["Time of Day"]=="Unknown"]
sharks_q2_time_day_unknown

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Time of Day,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Unknown,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Unknown,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,2018.05.24,6293.0,NaN,NaN
22,2018.04.24,24-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,"South Point, Gracetown",Surfing,Nathan Burch,M,NaN,"No injury, shark struck his leg",N,Afternoon,Unknown,"White shark, 3.5 m","B. Myatt, GSAF",2018.04.24-Burch.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.24,2018.04.24,6281.0,NaN,NaN
41,2018.02.17,18-Feb-2018,2018.0,Provoked,AUSTRALIA,Victoria,Westernport Bay,Kayak fishing for sharks,Brett Palmer,M,34,"Shark rammed kayak, no injury to occupant PRO...",N,Night,Unknown,NaN,"B. Myatt, GSAF",2018.02.17-Palmer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.02.17,2018.02.17,6262.0,NaN,NaN
51,2018.01.12,12-Jan-2018,2018.0,Unprovoked,BRAZIL,Fernando de Noronha,Conceicao Beach,Surfing,Ricardo Ferrari Bulhoes,M,20,Minor injury to left forearm,N,Late afternoon,Unknown,small shark,TrackingSharks.com,2018.01.12-Bulhoes.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.01.12,2018.01.12,6252.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6241,ND.0065,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Fishing from a small boat & put his hand in th...,male,M,25,Right hand severed,N,Afternoon,Unknown,NaN,B.W. Coad & L.A.J. Al-Hassan,ND-0065-deadfish.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0065,ND.0065,62.0,NaN,NaN
6242,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Unknown,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0,NaN,NaN
6243,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Unknown,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN,NaN
6259,ND.0044,1941-1945,0.0,Sea Disaster,NaN,NaN,NaN,A group of survivors on a raft for 17-days,C.,NaN,NaN,"FATAL, shark leapt into raft and bit the man w...",Y,Late afternoon,Unknown,1.2 m [4'] shark,"G.A. Llano in Airmen Against the Sea, p.69",ND-0044-C.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0044,ND.0044,44.0,NaN,NaN
6265,ND.0038,1941-1942,0.0,Unprovoked,IRAQ,Basrah,Shatt-el Arab River near a small boat stand,Swimming,male,M,13 or 14,"FATAL, left leg bitten with severe blood loss",Y,Afternoon,Unknown,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0038-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0038,ND.0038,38.0,NaN,NaN

In [1195]:
#lot's of info in the Time column still. I will assumed that everytime there's written for example
#"morning" in the "time" column, this correlates to actual "morning" in my "time of day column"

#remembering: ["Morning", "Afternoon", "Evening", "Night"]

#I will first identify what rows include the word morning (and then to the same for the remaining periods I've defined)
time_contains_word_morning = sharks_q2['Time'].str.contains('morning', case=False, na=False)

#and now locating these rows with the LLLLLLLLLLLoc (llllllllllabel) and change the entry in my time of day col:
sharks_q2.loc[time_contains_word_morning, 'Time of Day'] = "Morning"

time_contains_word_afternoon = sharks_q2['Time'].str.contains('afternoon', case=False, na=False)
sharks_q2.loc[time_contains_word_afternoon, 'Time of Day'] = "Afternoon"

time_contains_word_evening = sharks_q2['Time'].str.contains('evening', case=False, na=False)
sharks_q2.loc[time_contains_word_evening, 'Time of Day'] = "Evening"

time_contains_word_night = sharks_q2['Time'].str.contains('night', case=False, na=False)
sharks_q2.loc[time_contains_word_night, 'Time of Day'] = "Night"

In [1196]:
#rechecking:
sharks_q2_time_day_unknown = sharks_q2[sharks_q2["Time of Day"]=="Unknown"]
sharks_q2_time_day_unknown

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Time of Day,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
138,2017.06.02,02-Jun-2017,2017.0,Unprovoked,BAHAMAS,New Providence,Athol Island,Snorkeling,Tiffany Johnson,F,32,Right forearm severed,N,Shortly before 12h00,Unknown,Tiger shark,"Tribune 242, 6/2/2017",2017.06.02-Johnson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.02,2017.06.02,6165.0,NaN,NaN
215,2016.09.17.b,17-Sep-2016,2016.0,Unprovoked,USA,California,"Bunkers, Humboldt Bay, Eureka, Humboldt County",Surfing,Yuma,M,43,"No injury, board bitten",N,After noon,Unknown,NaN,"R. Collier, GSAF",2016.09.17.b-Yuma.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17.b,2016.09.17.b,6088.0,NaN,NaN
242,2016.07.20,20-Jul-2016,2016.0,Provoked,AUSTRALIA,Queensland,"20 k off The Spit, off the Gold Coast",Fishing,Scott van Burck,M,31,Laceration to left calf from hooked shark PROV...,N,After noon,Unknown,"reef shark, 1m","Nine News, 7/20/2016",2016.07.20-Burck.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.20,2016.07.20,6061.0,NaN,NaN
244,2016.07.16.b,16-Jul-2016,2016.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,female,F,9,Minor injury to leg,N,1300,Unknown,NaN,"Orlando Sentinel, 7/21/2016",2016.07.16.b-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.16.b,2016.07.16.b,6059.0,NaN,NaN
472,2014.11.29,29-Nov-2014,2014.0,Unprovoked,AUSTRALIA,Western Australia,"Pyramids Beach, Port Bouvard",Surfing,Cameron Pearman,M,13,Minor injuries to right leg,N,Sometime between 06h00 & 08hoo,Unknown,NaN,"The Sydney Morning Herald, 11/29/2014",2014.11.29-Pearman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.11.29,2014.11.29,5831.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5692,1891.06.11,11-Jun-1891,1891.0,Invalid,USA,Virginia,Hampton Roads,Fishing for sharks when he became entangled in...,John Howard,M,NaN,"Fatal, but death may have been due to drowning",Y,,Unknown,Shark involvement prior to death unconfirmed,"Washington Post, 6/12/1891, p.1",1891.06.11-JohnHoward.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1891.06.11,1891.06.11,611.0,NaN,NaN
5725,1888.08.14,14-Aug-1888,1888.0,Sea Disaster,CANADA,Nova Scotia,Off Sable Island,The steamships Thingvalla and Geiser collided,1 man,M,NaN,FATAL,Y,Before daybreak,Unknown,NaN,"Aurora Daiy Express, 8/18/1888",1888.08.14-Geiser-passenger.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1888.08.14,1888.08.14,578.0,NaN,NaN
5807,1881.09.05,05-Sep-1881,1881.0,Unprovoked,USA,North Carolina,"Elizabeth City, Pasquotank County",Bathing,Frank G. Hines,M,NaN,"FATAL, possible post-mortem bites",Y,A.M.,Unknown,NaN,"C. Creswell, GSAF",1881.09.05-Hines.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1881.09.05,1881.09.05,496.0,NaN,NaN
5900,1872.01.28,28-Jan-1872,1872.0,Invalid,Fiji,Lomaiviti Provine,"Levuka Point, Ovalau Island",boat capsized,Mr. Manning,M,NaN,Probable drowning,Y,dusk,Unknown,Shark involvement prior to death unconfirmed,"Empire, 2/20/1872",1872.01.28-Manning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1872.01.28,1872.01.28,403.0,NaN,NaN
5922,1868.05.13,13-May-1868,1868.0,Unprovoked,INDIA,Hoogly River,Ghat,Standing,male,M,35,"FATAL, upper left thigh, groin & buttocks seve...",Y,Before 10h30,Unknown,Identified as C. gangeticus by Dr. J. Fayrer,"J. Fayrer, M.D.",1868.05.13-Hindoo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1868.05.13,1868.05.13,381.0,NaN,NaN

In [1197]:
#time of day is unknown:
unknown_time_of_day_entries = sharks_q2.loc[sharks_q2["Time of Day"] == "Unknown", "Time"].unique()

unknown_time_of_day_entries

array(['Shortly before 12h00', 'After noon', '1300',
       'Sometime between 06h00 & 08hoo', '0830', 'Just before noon',
       '1600', 'Dawn', 'Midday', 'AM', 'A.M.', 'Dusk', 'Lunchtime',
       '15j45', '0500', 'Before 07h00', '"Just before 11h00"', 'Sunset',
       '  ', 'Just before sundown', '>08h00', '--', 'Just after 12h00',
       ' ', '\xa0 ', 'P.M.', 'Shortly before 13h00', '8:04 pm',
       'After Dusk', 'Noon', '2 hours after Opperman',
       '30 minutes after 1992.07.08.a', '>06h45', 'Between 06h00 & 07h20',
       '<07h30', 'X', '06j00', 'Prior to 10h37', 'Daybreak', '>12h00',
       'Just before dawn', ' 14h00', 'Daytime', 'Dark', '>17h00',
       'Midday.', '"After dark"', '2 hrs before sunset', '1500',
       '"shortly before dusk"', '>17h30', '>14h30', 'After 04h00',
       'Ship aban-doned at 03h10', 'After dusk',
       'FATAL  (Wire netting installed at local beaches after this incident.)',
       'Late afternon', '   ', 'Before daybreak', 'dusk', 'Before 10h30'],
      dtype=object)

In [1198]:
#just like I did with the countries, creating a dictionary to then tackle these sh*t values:
#time_categories = ["Morning", "Afternoon", "Evening", "Night"]
#time_categories_intervals = [5, 12, 17, 21, 24] 


time_of_day_correct_dict = {
    'Shortly before 12h00': 'Morning',
    'After noon': 'Afternoon',
    '1300': 'Afternoon',
    'Sometime between 06h00 & 08hoo': 'Morning',
    '0830': 'Morning',
    'Just before noon': 'Morning',
    '1600': 'Afternoon',
    'Dawn': 'Morning',
    'Midday': 'Morning',
    'AM': 'Morning',
    'A.M.': 'Morning',
    'Dusk': 'Evening',
    'Lunchtime': 'Morning',
    '15j45': 'Afternoon',
    '0500': 'Morning',
    'Before 07h00': 'Morning',
    '"Just before 11h00"': 'Morning',
    'Sunset': 'Afternoon',
    '  ': 'Unknown',
    'Just before sundown': 'Evening',
    '>08h00': 'Morning',
    '--': 'Unknown',
    'Just after 12h00': 'Afternoon',
    ' ': 'Unknown',
    '\xa0': 'Unknown',
    'P.M.': 'Afternoon',
    'Shortly before 13h00': 'Afternoon',
    '8:04 pm': 'Morning',
    'After Dusk': 'Night',
    'Noon': 'Afternoon',
    '2 hours after Opperman': 'Unknown',
    '30 minutes after 1992.07.08.a': 'Unknown', #JAJAJAJAJ AHAHAHA LOOOOOOL MDR OMG what is this even
    '>06h45': 'Morning',
    'Between 06h00 & 07h20': 'Morning',
    '<07h30': 'Morning',
    'X': 'Morning',
    '06j00': 'Morning',
    'Prior to 10h37': 'Morning',
    'Daybreak': 'Morning',
    '>12h00': 'Morning',
    'Just before dawn': 'Morning',
    '14h00': 'Afternoon',
    'Daytime': 'Morning',
    'Dark': 'Night',
    '>17h00': 'Afternoon',
    'Midday.': 'Afternoon',
    '"After dark"': 'Night',
    '2 hrs before sunset.': 'Evening',
    '1500': 'Afternoon',
    '"shortly before dusk"': 'Evening',
    '>17h30': 'Evening',
    '>14h30': 'Afternoon',
    'After 04h00': 'Morning',
    'Ship aban-doned at 03h10': 'Morning',
    'After dusk': 'Evening',
    'FATAL  (Wire netting installed at local beaches after this incident.)': 'Morning', #bro, wrong column
    'Late afternon': 'Evening',
    '   ': 'Unknown',
    'Before daybreak': 'Morning',
    'dusk': 'Evening',
    'Before 10h30': 'Morning',

}


#and now I replace these strange countries with the actual one:
sharks_q2.loc[sharks_q2['Time'].isin(time_of_day_correct_dict.keys()), 'Time of Day'] = sharks_q2['Time'].map(time_of_day_correct_dict)

In [1199]:
unknown_time_of_day_entries = sharks_q2.loc[sharks_q2["Time of Day"] == "Unknown", "Time"].unique()

unknown_time_of_day_entries

array(['  ', '--', ' ', '\xa0 ', '2 hours after Opperman',
       '30 minutes after 1992.07.08.a', ' 14h00', '2 hrs before sunset',
       '   '], dtype=object)

In [1200]:
#I'll remove these entries. 
sharks_q2 = sharks_q2.drop(sharks_q2[sharks_q2["Time of Day"] == "Unknown"].index)

In [1201]:
sharks_q2["Time of Day"].unique()

array(['Evening', 'Afternoon', 'Morning', 'Night'], dtype=object)

In [1202]:
#OK! So  Time of Day is ready to go!!!!!!

# now: sharks_q2_fatalities_and_time_cleaned

In [1203]:
#again, storing this as a new dataframe:

sharks_q2_fatalities_and_time_cleaned = sharks_q2.copy() #and now freezing it
#resetting the index and removing the duplicates:
sharks_q2_fatalities_and_time_cleaned = sharks_q2_fatalities_and_time_cleaned.reset_index(drop=True)
sharks_q2_fatalities_and_time_cleaned = sharks_q2_fatalities_and_time_cleaned.drop_duplicates(subset=['Case Number', 'Date', 'Country'], keep='first')
sharks_q2_fatalities_and_time_cleaned

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Time of Day,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,Evening,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,Afternoon,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,Morning,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN
4,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,Lower left leg bitten,N,17h00,Evening,"Bull shark, 6'","K.McMurray, TrackingSharks.com",2018.05.26.b-High.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b,2018.05.26.b,6295.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2801,ND.0065,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Fishing from a small boat & put his hand in th...,male,M,25,Right hand severed,N,Afternoon,Afternoon,NaN,B.W. Coad & L.A.J. Al-Hassan,ND-0065-deadfish.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0065,ND.0065,62.0,NaN,NaN
2802,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0,NaN,NaN
2803,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN,NaN
2804,ND.0044,1941-1945,0.0,Sea Disaster,NaN,NaN,NaN,A group of survivors on a raft for 17-days,C.,NaN,NaN,"FATAL, shark leapt into raft and bit the man w...",Y,Late afternoon,Afternoon,1.2 m [4'] shark,"G.A. Llano in Airmen Against the Sea, p.69",ND-0044-C.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0044,ND.0044,44.0,NaN,NaN
2805,ND.0038,1941-1942,0.0,Unprovoked,IRAQ,Basrah,Shatt-el Arab River near a small boat stand,Swimming,male,M,13 or 14,"FATAL, left leg bitten with severe blood loss",Y,Afternoon,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0038-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0038,ND.0038,38.0,NaN,NaN

In [1204]:
#exporting:
sharks_q2_fatalities_and_time_cleaned.to_csv('./data/Q2 attacks.csv', index=False)

## Cleaning "Type"

In [1205]:
#since I'll be crossing this column with the countries, my starting point for Q3 can be the df sharks_q1_countries_cleaned:
sharks_q3 = sharks_q1_countries_cleaned.copy()
sharks_q3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3343,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0,NaN,NaN,Unknown
3344,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN,NaN,Unknown
3345,ND.0051,Before 1957,0.0,Provoked,CUBA,Havana Province,Cojimar,"Shark fishing, knocked overboard",Sandrillio,M,50,"FATAL, hip bitten PROVOKED INCIDENT",Y,NaN,NaN,"F. Poli, pp.75, 81-83",ND-0051-Sandrillio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0051,ND.0051,49.0,NaN,NaN,Unknown
3346,ND.0026,Early 1930s,0.0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,16,FATAL,Y,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27.0,NaN,NaN,Unknown
3347,ND.0001,1845-1853,0.0,Unprovoked,SRI LANKA,Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

In [1206]:
sharks_q3["Type"].unique()

array(['Boating', 'Unprovoked', 'Invalid', 'Provoked', nan, 'Boat',
       'Sea Disaster'], dtype=object)

##### some qualitative inputs here:
I see that "sea disaster" equates to descriptions in the remaining columns (looking in particular at activity or fatality)
that suggest these people did not provke the incident. So I will change these entries to "Unprovoked". 

Boating, Boat and Boatomg will be a different category.
In the end I'll have 4 diff cats:
Boating
Provoked
Unprovoked
Questionable

In [1207]:
#1 replacing Boat and Boatomg with Boating:

sharks_q3['Type'] = sharks_q3['Type'].replace("Boatomg","Boating")
sharks_q3['Type'] = sharks_q3['Type'].replace("Boat","Boating")

sharks_q3["Type"].unique()

array(['Boating', 'Unprovoked', 'Invalid', 'Provoked', nan,
       'Sea Disaster'], dtype=object)

In [1208]:
#2 replacing Sea Disaster with Unprovoked:
sharks_q3['Type'] = sharks_q3['Type'].replace("Sea Disaster","Unprovoked")
sharks_q3["Type"].unique()

array(['Boating', 'Unprovoked', 'Invalid', 'Provoked', nan], dtype=object)

In [1209]:
#3 Assessing what to do with questiobale:
questionable_types_q3 = sharks_q3[sharks_q3["Type"]=="Questionable"]

questionable_types_q3

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1210]:
#just two entries, I'll check the PDFs.
#both seem to have been unprovoked:
sharks_q3['Type'] = sharks_q3['Type'].replace('Questionable', 'Unprovoked')

In [1211]:
#4. deciding what to do with the Invalid
invalid_types_q3 = sharks_q3[sharks_q3["Type"]=="Invalid"]

invalid_types_q3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
10,2018.05.13.a,13-May-2018,2018.0,Invalid,UNITED KINGDOM,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15,Invalid incident,"K. McMurray, TrackingSharks.com",2018.05.13.a-Berryman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a,2018.05.13.a,6290.0,NaN,NaN,Morning
21,2018.04.10.R,Reported 10-Apr-2018,2018.0,Invalid,BRAZIL,Alagoas,"Praia de Sauaçuhy, Maceió",Fishing,Josias Paz,M,56,Injury to ankle from marine animal trapped in ...,N,NaN,Shark involvement not confirmed,"K. McMurray, TrackingSharks.com",2018.04.10.R-Paz.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.10.R,2018.04.10.R,6272.0,NaN,NaN,Unknown
32,2018.02.11,11-Feb-2018,2018.0,Invalid,BRAZIL,"Boi Island, Victoria",Espirito Santo,Cleaning fish,Rosalida Souza,F,46,Lacerations to 4 toes of right foot,N,NaN,"Injury believed caused by an eel, not a shark",TrackingSharks.com,2018.02.11-Rosilda.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.02.11,2018.02.11,6259.0,NaN,NaN,Unknown
34,2018.02.01,01-Feb-2018,2018.0,Invalid,AUSTRALIA,Western Australia,"Avalon Point, Manurah",Spearfishing,Lucas Martin,M,14,"No injury no attack. This is considerd an ""enc...",N,NaN,2m shark,"The West Australian, 2/2/2018",2018.02.01-Martin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.02.01,2018.02.01,6257.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3255,1905.01.01,01-Jan-1905,1905.0,Invalid,AUSTRALIA,Victoria,Elwood,Bathing,Alfred Boldner,M,39,Reported to have been killed by a shark but 2 ...,NaN,NaN,Invalid,"Adelaide Advertiser, 1/3/1905",1905.01.01-Boldner.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1905.01.01,1905.01.01,802.0,NaN,NaN,Unknown
3264,1901.07.17,17-Jul-1901,1901.0,Invalid,ITALY,Syracuse,Capo Santa Croce,Swimming,Antonio Tornatori,M,20,"Disappeared, but shark involvement unconfirmed",NaN,NaN,Questionable,C. Moore. GSAF,1901.07.17-Antonio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1901.07.17,1901.07.17,757.0,NaN,NaN,Unknown
3270,1899.01.28,28-Jan-1899,1899.0,Invalid,AUSTRALIA,New South Wales,Newcastle,Bathing,Rose Sutcliffe,F,13,Drowning may mav preceded attack,NaN,NaN,Questionable,"Kalgoorlie Western Argus, 2/2/1899",1899.01.28-Sutcliffe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1899.01.28,1899.01.28,723.0,NaN,NaN,Unknown
3292,1881.10.16,16-Oct-1881,1881.0,Invalid,USA,Florida,"Pensacola Bay, Escambia County",Bathing,Anthony McDonald,M,18,FATAL,NaN,NaN,Shark involvement prior to death unconfirmed,"Pensacola Gazette, 10/18/1881; Fort Wayne Dail...",1881.10.16-McDonald.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1881.10.16,1881.10.16,497.0,NaN,NaN,Unknown
3318,1863.02.05,05-Feb-1863,1863.0,Invalid,SOUTH AFRICA,KwaZulu-Natal,"Back Beach, Durban","Swimming, caught in strong backwash & disappeared",Mr. J. Canham,M,26,3.2 m [10.5'] shark caught 9 days later contai...,NaN,NaN,Shark involvement prior to death unconfirmed,"M. Levine, GSAF; Times of Natal, 2/16/1863",1863.02.05-Canham.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1863.02.05,1863.02.05,346.0,NaN,NaN,Unknown

##### qualitative consideration:
lots of invalid results. Checking other columns to decided how to label these.
Tried to find a pattern in the "provoked" and the "unprovoked" but the majority of the key words are shared between them
(ex: can have "fishing" in the activity in both provoked and unprovoked). I'm enticed to label these the invalids as "questionable". For some other I will change them with a dictionary as we've done for 2 other vars.

In [1212]:
invalid_type_entries = sharks_q3.loc[sharks_q3["Type"] == "Invalid", "Activity"].unique()

invalid_type_entries

array(['Surfing', 'Fishing', 'Cleaning fish', 'Spearfishing',
       'Scuba Diving', 'Swimming', 'Fishing ', 'Wading', nan,
       'Feeding stingrays?', 'Floating', 'Treading water', 'Diving',
       'Swimming after falling overboard', 'Shark diving',
       'Diving for lobsters', 'Marathon swimming',
       'Dragging stranded shark into deeper water', 'Scuba diving',
       'Standing', 'Attempting to Kite surf from Egypt to Saudi Arabia',
       'Playing in the surf', 'Swimming after boat became disabled',
       'Spearfishing (free diving)', 'Crawling', 'Body surfing',
       'Free diving', 'Boogie boarding, kicked at object in the water',
       'Swept out to sea by the tsunami, she clung  to a log for 24 hours',
       'Free diving & spearfishing', 'Snorkeling', 'Unknown',
       'Fishing (Drowned 2-Apr-2002)', 'Wreck / Technical diving',
       'Hiking on the beach', 'Attempting to catch a crocodile',
       'Shipwrecked', 'Walking', 'Kayaking', 'SCUBA diving',
       'Boogie boarding', 'Tech diving ', 'Murder victim',
       'Scuba diving ', 'Boat capsized?', 'Hard hat diving',
       'Spearfishing on Scuba', 'Spearfishing / Scuba diving',
       'Motor boat Rebel Belle lost', 'Spearfishing / free diving',
       'Spearfishing ', 'Attempting to swim across the Atlantic Ocean',
       'Commercial fishing vessel, Ev-nn, struck object & sank. Ken Crosby and  Jame & Ann Dumas adrift on makeshift raft.',
       "Overcome by CO fumes, fell overboard from 36' fishing cruiser & prop slashed arm",
       'Fishing, slipped on rocks & fell into sea', 'Splashing ',
       'Fell overboard, prop slashed arm',
       'Free diving / photography, kneeling on sand',
       'The 240-ton motor vessel Pilar II with 100 people on board capsized in high winds & rough seas',
       'Diving off jetty', 'Bathing', 'fishing boat exploded & sank',
       'Disappeared 11 days earlier, probable homicide victim',
       'Swimming ', 'Reported swept away by waves while gathering opihi',
       '.', 'Swimming, caught in strong backwash & disappeared'],
      dtype=object)

In [1213]:
#array(['Boating', 'Unprovoked', 'Invalid', 'Provoked', 'Questionable',nan], dtype=object)

#reasoning behind my labelling will be: activities that expose people to danger will be considered provoked.

correcting_type_based_on_activity = {
    'Boat capsized, swimming ashore': 'Unprovoked',
    'Swimming, caught in strong backwash & disappeared': 'Unprovoked',
    'Fell overboard, prop slashed arm': 'Unprovoked',
    'Aircraft crashed into sea': 'Unprovoked',
    'Floating on a raft': 'Unprovoked',
    'S2F-1 airplane crashed immediately after carrier take-off': 'Unprovoked',
    'boat capsized during filming': 'Unprovoked',
    'Standing in water with child in her arms': 'Unprovoked',
    'Bathing': 'Unprovoked',
    'Disappeared 11 days earlier, probable homicide victim': 'Unprovoked',
    'Air disaster': 'Unprovoked',
    'Fishing, thrown into water by heavy sea, clinging to rocks at the water line': 'Unprovoked',
    'On December 28, 1908, an earthquake, followed by tsunamis, destroyed coastal towns in Silcily and southern Italy, killing more than 100,000 people': 'Unprovoked',
    'Reached out to disentangle rope & fell overboard': 'Unprovoked',
    "Zosimo & his son, Jeffrey Popa, failed to return from overnight fishing trip in a 14' boat, Boat apparently sank, debris recovered but his son & boat were never found": 'Unprovoked',
    'Wading, knocked down & swept away by large waves': 'Unprovoked',
    'Fell overboard  from the Taiwanese fishing trawler Lien Cheng Feu ': 'Unprovoked',
    "Boat capsized between O'ahu & Molokai": 'Unprovoked',
    'Diving, retrieving film package from Titan 3C rocket': 'Unprovoked',
    'Aircraft exploded': 'Unprovoked',
    'Motor boat Rebel Belle lost': 'Unprovoked',
    'Bather': 'Unprovoked',
    'Boat Miss Becky  sank 12 miles from shore': 'Unprovoked',
    'Commercial fishing vessel, Ev-nn, struck object & sank. Ken Crosby and  Jame & Ann Dumas adrift on makeshift raft.': 'Unprovoked',
    'S.S. Marine Sulphur Queen, laden with molten sulphur was bound from Beaumont, Texas for Norfolk, VA, when she disappeared with 39 on board': 'Unprovoked',
    'Fishing, slipped on rocks & fell into sea': 'Unprovoked',
    'Netting sharks': 'Provoked',
    'Floating': 'Unprovoked',
    'Surfing & filming dolphins': 'Unprovoked',
    'Swimming after falling overboard': 'Unprovoked',
    'Diving for lobsters': 'Unprovoked',
    'Marathon swimming': 'Unprovoked',
    'Standing': 'Unprovoked',
    'Attempting to Kite surf from Egypt to Saudi Arabia': 'Unprovoked',
    'Surf skiing': 'Unprovoked',
    'Playing in the surf': 'Unprovoked',
    'Swimming after boat became disabled': 'Unprovoked',
    'Body surfing': 'Unprovoked',
    'Swept out to sea by the tsunami, she clung  to a log for 24 hours': 'Unprovoked',
    'Five men on makeshift raft after their 10 m fishing boat  capsized and sank in rough seas. Survivors rescued after  7.5 hours in the water': 'Unprovoked',
    'Swimming to shore from boat or kayak': 'Unprovoked',
    'Hiking on the beach': 'Unprovoked',
    'Shipwrecked': 'Unprovoked',
    'Murder victim': 'Unprovoked',
    'Fell from cliff while fishing & disappeared in strong current': 'Unprovoked',
    'Attempting to illegally enter the USA': 'Unprovoked',
    'Kayaking (returning from spearfishing)': 'Provoked',
    'Cage Diving': 'Provoked', 
    'Shark diving': 'Provoked', 
    'Dragging stranded shark into deeper water': 'Provoked',
    'Spearfishing (free diving)': 'Provoked',
    'Crayfishing': 'Provoked',
    'Free diving & spearfishing': 'Provoked',
    'Attempting to catch a crocodile': 'Provoked',
    'Spearfishing on Scuba': 'Provoked',
    'Spearfishing / Scuba diving': 'Provoked',
    'Suicide': 'Provoked',
    'Jumped overboard': 'Provoked',

}


#and now I replace these strange entries with the actual one:
sharks_q3.loc[sharks_q3['Activity'].isin(correcting_type_based_on_activity.keys()), 'Type'] = sharks_q3['Type'].map(correcting_type_based_on_activity)

In [1214]:
invalid_types_q3 = sharks_q3[sharks_q3["Type"]=="Invalid"]

invalid_types_q3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
10,2018.05.13.a,13-May-2018,2018.0,Invalid,UNITED KINGDOM,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15,Invalid incident,"K. McMurray, TrackingSharks.com",2018.05.13.a-Berryman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a,2018.05.13.a,6290.0,NaN,NaN,Morning
21,2018.04.10.R,Reported 10-Apr-2018,2018.0,Invalid,BRAZIL,Alagoas,"Praia de Sauaçuhy, Maceió",Fishing,Josias Paz,M,56,Injury to ankle from marine animal trapped in ...,N,NaN,Shark involvement not confirmed,"K. McMurray, TrackingSharks.com",2018.04.10.R-Paz.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.10.R,2018.04.10.R,6272.0,NaN,NaN,Unknown
32,2018.02.11,11-Feb-2018,2018.0,Invalid,BRAZIL,"Boi Island, Victoria",Espirito Santo,Cleaning fish,Rosalida Souza,F,46,Lacerations to 4 toes of right foot,N,NaN,"Injury believed caused by an eel, not a shark",TrackingSharks.com,2018.02.11-Rosilda.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.02.11,2018.02.11,6259.0,NaN,NaN,Unknown
34,2018.02.01,01-Feb-2018,2018.0,Invalid,AUSTRALIA,Western Australia,"Avalon Point, Manurah",Spearfishing,Lucas Martin,M,14,"No injury no attack. This is considerd an ""enc...",N,NaN,2m shark,"The West Australian, 2/2/2018",2018.02.01-Martin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.02.01,2018.02.01,6257.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3206,1920.07.14,14-Jul-1920,1920.0,Invalid,USA,New York,"Woodcliff Channel, Freeport, Long Island",Swimming,Thomas McCann,M,30,Thought to have been taken by a shark. Body wa...,NaN,NaN,Questionable,"V.M. Coppleson (1958), p.151",1920.07.14-McCann.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1920.07.14,1920.07.14,1052.0,NaN,NaN,Unknown
3241,1909.04.10,10-Apr-1909,1909.0,Invalid,USA,Hawaii,"Pa'uwela, Maui",Reported swept away by waves while gathering o...,Mrs. Ah Kim Chong,F,19,Search party saw a large shark devour what ap...,NaN,NaN,Questionable,"Honolulu Star Advertisr, 4/18/1909; J. Borg, p...",1909.04.10-Chong.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1909.04.10,1909.04.10,881.0,NaN,NaN,Unknown
3247,1906.04.02.R,Reported 02-April 1906,1906.0,Invalid,AUSTRALIA,New South Wales,Moodie Beach,.,Herbert Mills,M,18,Cause of death may have been downing,NaN,NaN,Questionable,".Morning Bulletin, 4/3/1906",1906.04.02.R-Mills.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1906.04.02.R,1906.04.02.R,822.0,NaN,NaN,Unknown
3251,1905.07.25.R,Reported 25-Jul-1905,1905.0,Invalid,ITALY,NaN,Naples,NaN,boy,M,8,"Body recovered from shark, probable drowning a...",NaN,NaN,Shark involvement prior to death was not confi...,"C. Moore, GSAF",1905.07.25.R-Naples.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1905.07.25.R,1905.07.25.R,810.0,NaN,NaN,Unknown
3264,1901.07.17,17-Jul-1901,1901.0,Invalid,ITALY,Syracuse,Capo Santa Croce,Swimming,Antonio Tornatori,M,20,"Disappeared, but shark involvement unconfirmed",NaN,NaN,Questionable,C. Moore. GSAF,1901.07.17-Antonio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1901.07.17,1901.07.17,757.0,NaN,NaN,Unknown

In [1215]:
#dropping the remaining values:
sharks_q3 = sharks_q3.drop(sharks_q3[sharks_q3["Type"] == "Invalid"].index)

In [1216]:
#5. deciding what to do with nans. Will take on the same approach:
nans_in_sharks_q3 = sharks_q3[sharks_q3["Type"].isna()]
nans_in_sharks_q3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
1,2018.06.18,18-Jun-2018,2018.0,NaN,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
6,2018.05.26.a,26-May-2018,2018.0,NaN,USA,Florida,"Daytona Beach, Volusia County",Standing,male,M,12,Minor injury to foot,N,14h00,NaN,"K. McMurray, Tracking Sharks.com",2018.05.26.a-DaytonaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.a,2018.05.26.a,6294.0,NaN,NaN,Afternoon
57,2017.09.16.b,16-Sep-2017,2017.0,NaN,SPAIN,Canary Islands,Gran Canaria,Body surfing,male,M,13,Lacerations to right foot,N,NaN,"Porbeagle, 1.5 m",Turismo La Aldea,2017.09.16.b-GrandCanary.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.16.b,2017.09.16.b,6221.0,NaN,NaN,Unknown
133,2016.11.14,14-Nov-2016,2016.0,NaN,USA,Hawaii,"Kamaole Beach Park I, Maui",Floating,Barbara Zawacki,F,58,Injuries to right calf and thigh,N,10h30,Tiger shark,"Maui News, 11/14/2016",2016.11.14-Zawacki.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.11.14,2016.11.14,6104.0,NaN,NaN,Morning
178,2016.06.21.b,21-Jun-2016,2016.0,NaN,USA,South Carolina,"North Myrtle Beach, Horry County",Floating,Jeff Schott,M,42,Lacerations and punctures to foot,N,15h25,3' to 5' shark,"C. Creswell, GSAF",2016.06.21.b-Schott.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.06.21.b,2016.06.21.b,6044.0,NaN,NaN,Afternoon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3314,1868.05.13,13-May-1868,1868.0,NaN,INDIA,Hoogly River,Ghat,Standing,male,M,35,"FATAL, upper left thigh, groin & buttocks seve...",Y,Before 10h30,Identified as C. gangeticus by Dr. J. Fayrer,"J. Fayrer, M.D.",1868.05.13-Hindoo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1868.05.13,1868.05.13,381.0,NaN,NaN,Unknown
3318,1863.02.05,05-Feb-1863,1863.0,NaN,SOUTH AFRICA,KwaZulu-Natal,"Back Beach, Durban","Swimming, caught in strong backwash & disappeared",Mr. J. Canham,M,26,3.2 m [10.5'] shark caught 9 days later contai...,NaN,NaN,Shark involvement prior to death unconfirmed,"M. Levine, GSAF; Times of Natal, 2/16/1863",1863.02.05-Canham.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1863.02.05,1863.02.05,346.0,NaN,NaN,Unknown
3319,1863.01.10,10-Jan-1863,1863.0,NaN,AUSTRALIA,New South Wales,"""Bellynahinch"" on the Manning River",Bathing,James Brown,M,17,FATAL,Y,Evening,NaN,"G.P. Whitley, p.259",1863.01.10-Brown.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1863.01.10,1863.01.10,345.0,NaN,NaN,Unknown
3324,1858.03.14,14-Mar-1858,1858.0,NaN,AUSTRALIA,Victoria,Hobson Bay,Bathing,Adolphe Bollander,M,22,FATAL,Y,15h00,NaN,"Moreton Bay Courier, 3/31/1858",1858.03.14-Bollander.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1858.03.14,1858.03.14,312.0,NaN,NaN,Afternoon
3346,ND.0026,Early 1930s,0.0,NaN,BELIZE,NaN,NaN,Standing,a servant,M,16,FATAL,Y,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27.0,NaN,NaN,Unknown

In [1217]:
nan_entries_in_type = sharks_q3.loc[sharks_q3["Type"].isna(), "Activity"].unique()

nan_entries_in_type

array(['Standing', 'Body surfing', 'Floating', 'Surfing',
       'Swimming after falling overboard', 'Shark diving',
       'Diving for lobsters', 'Marathon swimming', 'Playing in the surf',
       'Dragging stranded shark into deeper water', 'Bathing',
       'Attempting to Kite surf from Egypt to Saudi Arabia',
       'Swimming after boat became disabled',
       'Spearfishing (free diving)',
       'Swept out to sea by the tsunami, she clung  to a log for 24 hours',
       'Free diving & spearfishing', 'Surf skiing', 'Floating on a raft',
       'Hiking on the beach', 'Attempting to catch a crocodile',
       'Shipwrecked', 'Murder victim', 'Spearfishing / Scuba diving',
       'Crayfishing', 'Spearfishing on Scuba',
       'Motor boat Rebel Belle lost',
       'Commercial fishing vessel, Ev-nn, struck object & sank. Ken Crosby and  Jame & Ann Dumas adrift on makeshift raft.',
       'Fishing, slipped on rocks & fell into sea',
       'Fell overboard, prop slashed arm',
       'Disappeared 11 days earlier, probable homicide victim',
       'Swimming, caught in strong backwash & disappeared'], dtype=object)

In [1218]:
correcting_type_based_on_activity_in_nan = {
    'Boat capsized, swimming ashore': 'Unprovoked',
    'Swimming, caught in strong backwash & disappeared': 'Unprovoked',
    'Fell overboard, prop slashed arm': 'Unprovoked',
    'Aircraft crashed into sea': 'Unprovoked',
    'Floating on a raft': 'Unprovoked',
    'S2F-1 airplane crashed immediately after carrier take-off': 'Unprovoked',
    'boat capsized during filming': 'Unprovoked',
    'Standing in water with child in her arms': 'Unprovoked',
    'Bathing': 'Unprovoked',
    'Disappeared 11 days earlier, probable homicide victim': 'Unprovoked',
    'Air disaster': 'Unprovoked',
    'Fishing, thrown into water by heavy sea, clinging to rocks at the water line': 'Unprovoked',
    'On December 28, 1908, an earthquake, followed by tsunamis, destroyed coastal towns in Silcily and southern Italy, killing more than 100,000 people': 'Unprovoked',
    'Reached out to disentangle rope & fell overboard': 'Unprovoked',
    "Zosimo & his son, Jeffrey Popa, failed to return from overnight fishing trip in a 14' boat, Boat apparently sank, debris recovered but his son & boat were never found": 'Unprovoked',
    'Wading, knocked down & swept away by large waves': 'Unprovoked',
    'Fell overboard  from the Taiwanese fishing trawler Lien Cheng Feu ': 'Unprovoked',
    "Boat capsized between O'ahu & Molokai": 'Unprovoked',
    'Diving, retrieving film package from Titan 3C rocket': 'Unprovoked',
    'Aircraft exploded': 'Unprovoked',
    'Motor boat Rebel Belle lost': 'Unprovoked',
    'Bather': 'Unprovoked',
    'Boat Miss Becky  sank 12 miles from shore': 'Unprovoked',
    'Commercial fishing vessel, Ev-nn, struck object & sank. Ken Crosby and  Jame & Ann Dumas adrift on makeshift raft.': 'Unprovoked',
    'S.S. Marine Sulphur Queen, laden with molten sulphur was bound from Beaumont, Texas for Norfolk, VA, when she disappeared with 39 on board': 'Unprovoked',
    'Fishing, slipped on rocks & fell into sea': 'Unprovoked',
    'Netting sharks': 'Provoked',
    'Floating': 'Unprovoked',
    'Surfing & filming dolphins': 'Unprovoked',
    'Swimming after falling overboard': 'Unprovoked',
    'Diving for lobsters': 'Unprovoked',
    'Marathon swimming': 'Unprovoked',
    'Standing': 'Unprovoked',
    'Attempting to Kite surf from Egypt to Saudi Arabia': 'Unprovoked',
    'Surf skiing': 'Unprovoked',
    'Playing in the surf': 'Unprovoked',
    'Swimming after boat became disabled': 'Unprovoked',
    'Body surfing': 'Unprovoked',
    'Swept out to sea by the tsunami, she clung  to a log for 24 hours': 'Unprovoked',
    'Five men on makeshift raft after their 10 m fishing boat  capsized and sank in rough seas. Survivors rescued after  7.5 hours in the water': 'Unprovoked',
    'Swimming to shore from boat or kayak': 'Unprovoked',
    'Hiking on the beach': 'Unprovoked',
    'Shipwrecked': 'Unprovoked',
    'Murder victim': 'Unprovoked',
    'Fell from cliff while fishing & disappeared in strong current': 'Unprovoked',
    'Attempting to illegally enter the USA': 'Unprovoked',
    'Kayaking (returning from spearfishing)': 'Provoked',
    'Cage Diving': 'Provoked', 
    'Shark diving': 'Provoked', 
    'Dragging stranded shark into deeper water': 'Provoked',
    'Spearfishing (free diving)': 'Provoked',
    'Crayfishing': 'Provoked',
    'Free diving & spearfishing': 'Provoked',
    'Attempting to catch a crocodile': 'Provoked',
    'Spearfishing on Scuba': 'Provoked',
    'Spearfishing / Scuba diving': 'Provoked',
    'Suicide': 'Provoked',
    'Jumped overboard': 'Provoked',
}
    
    

#and now I replace these strange entries with the actual one:
sharks_q3.loc[sharks_q3['Activity'].isin(correcting_type_based_on_activity_in_nan.keys()), 'Type'] = sharks_q3['Type'].map(correcting_type_based_on_activity_in_nan)

In [1219]:
#dropping the remaining missing values:
sharks_q3 = sharks_q3.dropna(subset=['Type'])

# now: sharks_q3_countries_and_type_cleaned

In [1220]:
#exporting:
sharks_q3_countries_and_type_cleaned.to_csv('./data/Q3 attacks.csv', index=False)

In [1221]:
#saving the dataframe as a ready to use after country and type have been cleaned:
sharks_q3_countries_and_type_cleaned = sharks_q3 #and now freezing
#resetting the index and removing the duplicates:
sharks_q3_countries_and_type_cleaned = sharks_q3_countries_and_type_cleaned.reset_index(drop=True)
sharks_q3_countries_and_type_cleaned = sharks_q3_countries_and_type_cleaned.drop_duplicates(subset=['Case Number', 'Date', 'Country'], keep='first')
sharks_q3_countries_and_type_cleaned

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
2,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
3,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,Lower left leg bitten,N,17h00,"Bull shark, 6'","K.McMurray, TrackingSharks.com",2018.05.26.b-High.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b,2018.05.26.b,6295.0,NaN,NaN,Evening
4,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,2018.05.24,6293.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2928,ND.0065,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Fishing from a small boat & put his hand in th...,male,M,25,Right hand severed,N,Afternoon,NaN,B.W. Coad & L.A.J. Al-Hassan,ND-0065-deadfish.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0065,ND.0065,62.0,NaN,NaN,Unknown
2929,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0,NaN,NaN,Unknown
2930,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN,NaN,Unknown
2931,ND.0051,Before 1957,0.0,Provoked,CUBA,Havana Province,Cojimar,"Shark fishing, knocked overboard",Sandrillio,M,50,"FATAL, hip bitten PROVOKED INCIDENT",Y,NaN,NaN,"F. Poli, pp.75, 81-83",ND-0051-Sandrillio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0051,ND.0051,49.0,NaN,NaN,Unknown
2932,ND.0001,1845-1853,0.0,Unprovoked,SRI LANKA,Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

## Cleaning "Year"

In [1222]:
#since I will cross the year with sex and countries but countries are clean already, that's my starting point:
sharks_q4 = sharks_q1_countries_cleaned.copy()
sharks_q4

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3343,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0,NaN,NaN,Unknown
3344,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN,NaN,Unknown
3345,ND.0051,Before 1957,0.0,Provoked,CUBA,Havana Province,Cojimar,"Shark fishing, knocked overboard",Sandrillio,M,50,"FATAL, hip bitten PROVOKED INCIDENT",Y,NaN,NaN,"F. Poli, pp.75, 81-83",ND-0051-Sandrillio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0051,ND.0051,49.0,NaN,NaN,Unknown
3346,ND.0026,Early 1930s,0.0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,16,FATAL,Y,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27.0,NaN,NaN,Unknown
3347,ND.0001,1845-1853,0.0,Unprovoked,SRI LANKA,Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

In [1223]:
sharks_q4["Year"].unique()

array([2018., 2017.,   nan, 2016., 2015., 2014., 2013., 2012., 2011.,
       2010., 2009., 2008., 2007., 2006., 2005., 2004., 2003., 2002.,
       2001., 2000., 1999., 1998., 1997., 1996., 1995., 1984., 1994.,
       1993., 1992., 1991., 1990., 1989., 1969., 1988., 1987., 1986.,
       1985., 1983., 1982., 1981., 1980., 1979., 1978., 1977., 1976.,
       1975., 1974., 1973., 1972., 1971., 1970., 1968., 1967., 1966.,
       1965., 1964., 1963., 1962., 1961., 1960., 1959., 1958., 1957.,
       1956., 1955., 1954., 1953., 1952., 1951., 1950., 1949., 1948.,
       1947., 1946., 1945., 1944., 1943., 1942., 1941., 1940., 1939.,
       1938., 1937., 1936., 1935., 1934., 1933., 1932., 1931., 1930.,
       1929., 1928., 1927., 1926., 1925., 1924., 1923., 1922., 1921.,
       1920., 1919., 1918., 1916., 1915., 1914., 1913., 1912., 1911.,
       1909., 1908., 1907., 1906., 1905., 1904., 1903., 1902., 1901.,
       1900., 1899., 1898., 1896., 1895., 1894., 1892., 1890., 1888.,
       1887., 1886., 1883., 1881., 1880., 1879., 1878., 1877., 1875.,
       1873., 1871., 1870., 1868., 1865., 1864., 1863., 1862., 1859.,
       1858., 1856., 1848., 1847., 1842., 1839., 1837., 1830., 1828.,
       1817., 1749., 1703.,    0.])

In [1224]:
#Plan of action:
#1. tackle strange values (500, 5, 0)
#2. tackle nan

In [1225]:
sharks_q4_year_is_500 = sharks_q4[sharks_q4["Year"]==500]
sharks_q4_year_is_500
#apparently 500 is actually correct!

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1226]:
sharks_q4_year_is_5 = sharks_q4[sharks_q4["Year"]==5]
sharks_q4_year_is_5
#and so is 5!

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1227]:
sharks_q4_year_is_0 = sharks_q4[sharks_q4["Year"]==0]
sharks_q4_year_is_0
#and so is 5!

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
3336,ND-0151,Before Oct-2009,0.0,Unprovoked,PANAMA,Bocas del Toro Province,Red Frog Beach,Swimming/,male,M,20,FATAL,Y,NaN,NaN,C. Mendieta & A. Duarte,ND-0151-Panama.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0151,ND-0151,119.0,NaN,NaN,Unknown
3337,ND-0139,1880-1899,0.0,Unprovoked,AUSTRALIA,Queensland,Boonooroo,NaN,Lassie,F,15,Foot severed,N,NaN,NaN,"Courier Mail, 6/30/1951",ND-0139-Lassie.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0139,ND-0139,114.0,NaN,NaN,Unknown
3338,ND-0123,Before 2009,0.0,Unprovoked,USA,Florida,NaN,Shark tagging,Danniell Washington,F,21,Severe abrasion to forearm from captive shark ...,N,18h00,"Blacktip shark, 5'",Daniell Washington,ND-0123-Daniell-Washington.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0123,ND-0123,103.0,NaN,NaN,Evening
3339,ND.0087,"No date, Before 1975",0.0,Provoked,USA,Florida,"Riviera Beach, Palm Beach County",Skin diving. Grabbed shark's tail; shark turne...,Carl Bruster,M,19,"Ankle punctured & lacerated, hands abraded PRO...",N,NaN,"Nurse shark, 2.1 m [7']","R. Skocik, p.176",ND-0087-Carl-Bruster.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0087,ND.0087,77.0,NaN,NaN,Unknown
3340,ND.0069,Before 1962,0.0,Unprovoked,FIJI,NaN,NaN,Spearfishing,Dalton Baldwin,M,27,"No injury, bumped by shark which took speared ...",N,NaN,1.8 m [6'] shark,"V. M. Coppleson (1962), p.253",ND-0069-Dalton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0069,ND.0069,65.0,NaN,NaN,Unknown
3341,ND.0068,Before 1962,0.0,Unprovoked,MOZAMBIQUE,Maputo Province,Santa Maria Peninsula,Skindiving,Les Bishop,M,36,Bumped by sharks,N,NaN,"""A pack of sharks""",L. Bishop; V.M. Coppleson (1962),ND-0068-LesBishop.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0068,ND.0068,64.0,NaN,NaN,Unknown
3342,ND.0065,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Fishing from a small boat & put his hand in th...,male,M,25,Right hand severed,N,Afternoon,NaN,B.W. Coad & L.A.J. Al-Hassan,ND-0065-deadfish.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0065,ND.0065,62.0,NaN,NaN,Unknown
3343,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0,NaN,NaN,Unknown
3344,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN,NaN,Unknown
3345,ND.0051,Before 1957,0.0,Provoked,CUBA,Havana Province,Cojimar,"Shark fishing, knocked overboard",Sandrillio,M,50,"FATAL, hip bitten PROVOKED INCIDENT",Y,NaN,NaN,"F. Poli, pp.75, 81-83",ND-0051-Sandrillio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0051,ND.0051,49.0,NaN,NaN,Unknown
3346,ND.0026,Early 1930s,0.0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,16,FATAL,Y,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27.0,NaN,NaN,Unknown
3347,ND.0001,1845-1853,0.0,Unprovoked,SRI LANKA,Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown

In [1228]:
sharks_q4_year_is_0_uniques = sharks_q4.loc[sharks_q4["Year"]==0, "Date"].unique()

sharks_q4_year_is_0_uniques

array(['Before Oct-2009', '1880-1899', 'Before 2009',
       'No date, Before  1975', 'Before 1962', '1960s', 'Before 1957',
       'Early 1930s', '1845-1853'], dtype=object)

In [1229]:
#Actually these dates are not precise at all. This is giving me nothing. I'll drop these values.
sharks_q4 = sharks_q4.drop(sharks_q4[sharks_q4["Year"]==0].index)
sharks_q4

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3331,1830.07.26,26-Jul-1830,1830.0,Unprovoked,USA,Massachusetts,"Swampscott, Essex County","Fishing from dory, shark upset boat & he fell ...",Joseph Blaney,M,52,FATAL,Y,NaN,NaN,"Huron Sun, 8/3/1830",1830.07.26-JosephBlaney.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1830.07.26,1830.07.26,214.0,NaN,NaN,Unknown
3332,1828.09.28,28-Sep-1828,1828.0,Unprovoked,SIERRA LEONE,Western Area,"River Sierra Leone, 35 miles upriver from Fre...","British ship, Britannia, was loading lumber. ...","Thomas Corrigle, an apprentice from the ship",M,17,"Left arm severed 2.5"" from elbow, groin, abdom...",N,NaN,NaN,Account by J. Boyle,1828.09.28-Corrigle.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1828.09.28,1828.09.28,207.0,NaN,NaN,Unknown
3333,1817.05.11,11-May-1817,1817.0,Unprovoked,SRI LANKA,Western Province,Colombo,Swimming,William May,M,22,FATAL,Y,Evening,NaN,Edinburgh Advertiser. 11/4/1817; R. DeSilva,1817.05.11-May.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1817.05.11,1817.05.11,189.0,NaN,NaN,Unknown
3334,1749.00.00,1749,1749.0,Unprovoked,CUBA,Havana Province,Havana Harbor,Swimming,Brook Watson,M,14,Right leg severed at knee. In 1796 he became ...,N,NaN,NaN,GSAF,1749.00.00-Watson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1749.00.00,1749.00.00,151.0,NaN,NaN,Unknown
3335,1703.03.26,26-Mar-1703,1703.0,Unprovoked,BARBADOS,Southwest coast,Carlisle Bay,Swimming,"Samuel Jennings, a deserter from the British f...",M,19,"Hand and foot severely bitten, surgically ampu...",N,Night,NaN,"W.R.Cutter, Vol.1, p.252",1703.03.26-Jennings.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1703.03.26,1703.03.26,143.0,NaN,NaN,Unknown

# now: sharks_q4_countries_and_year_cleaned

In [1230]:
#freezing this dataframe:

sharks_q4_countries_and_year_cleaned = sharks_q4.copy()
#resetting the index and removing the duplicates:
sharks_q4_countries_and_year_cleaned = sharks_q4_countries_and_year_cleaned.reset_index(drop=True)
sharks_q4_countries_and_year_cleaned = sharks_q4_countries_and_year_cleaned.drop_duplicates(subset=['Case Number', 'Date', 'Country'], keep='first')
sharks_q4_countries_and_year_cleaned

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3331,1830.07.26,26-Jul-1830,1830.0,Unprovoked,USA,Massachusetts,"Swampscott, Essex County","Fishing from dory, shark upset boat & he fell ...",Joseph Blaney,M,52,FATAL,Y,NaN,NaN,"Huron Sun, 8/3/1830",1830.07.26-JosephBlaney.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1830.07.26,1830.07.26,214.0,NaN,NaN,Unknown
3332,1828.09.28,28-Sep-1828,1828.0,Unprovoked,SIERRA LEONE,Western Area,"River Sierra Leone, 35 miles upriver from Fre...","British ship, Britannia, was loading lumber. ...","Thomas Corrigle, an apprentice from the ship",M,17,"Left arm severed 2.5"" from elbow, groin, abdom...",N,NaN,NaN,Account by J. Boyle,1828.09.28-Corrigle.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1828.09.28,1828.09.28,207.0,NaN,NaN,Unknown
3333,1817.05.11,11-May-1817,1817.0,Unprovoked,SRI LANKA,Western Province,Colombo,Swimming,William May,M,22,FATAL,Y,Evening,NaN,Edinburgh Advertiser. 11/4/1817; R. DeSilva,1817.05.11-May.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1817.05.11,1817.05.11,189.0,NaN,NaN,Unknown
3334,1749.00.00,1749,1749.0,Unprovoked,CUBA,Havana Province,Havana Harbor,Swimming,Brook Watson,M,14,Right leg severed at knee. In 1796 he became ...,N,NaN,NaN,GSAF,1749.00.00-Watson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1749.00.00,1749.00.00,151.0,NaN,NaN,Unknown
3335,1703.03.26,26-Mar-1703,1703.0,Unprovoked,BARBADOS,Southwest coast,Carlisle Bay,Swimming,"Samuel Jennings, a deserter from the British f...",M,19,"Hand and foot severely bitten, surgically ampu...",N,Night,NaN,"W.R.Cutter, Vol.1, p.252",1703.03.26-Jennings.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1703.03.26,1703.03.26,143.0,NaN,NaN,Unknown

![Finally cleaning the last variable!!!](https://media.giphy.com/media/Quh1CAKOTRCl9VVU3f/giphy.gif)

### Finally cleaning the last variable
### Finally cleaning the last variable
### Finally cleaning the last variable
### Finally cleaning the last variable

## Cleaning "Sex"

In [1231]:
sharks_q4_countries_and_year_cleaned["Sex "].unique()

array(['F', 'M', 'M ', nan, 'lli'], dtype=object)

In [1232]:
#b*tch ass column has got a space. Let's rename it:
sharks_q4_countries_and_year_cleaned.rename(columns={"Sex ":"Sex"},inplace=True)

In [296]:
sharks_q4_countries_and_year_cleaned["Sex"].unique()

array(['F', 'M', nan, 'M ', 'lli', 'N', '.'], dtype=object)

In [1233]:
#Plan of action:
#1. tackle "M "
#2. tackle "N"
#3. tackle "lli"
#4. tackle "."
#5. tackle nan

In [1234]:
#1
sharks_q4_countries_and_year_cleaned['Sex'] = sharks_q4_countries_and_year_cleaned['Sex'].str.strip()
sharks_q4_countries_and_year_cleaned["Sex"].unique()

array(['F', 'M', nan, 'lli'], dtype=object)

In [1235]:
#2
sharks_q4_countries_and_year_cleaned_sex_is_N = sharks_q4_countries_and_year_cleaned[sharks_q4_countries_and_year_cleaned["Sex"]=="N"]
sharks_q4_countries_and_year_cleaned_sex_is_N

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex, Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1236]:
#PDF doesn't give much, it was a group apparently. This var will have F/M/Not Specified
sharks_q4_countries_and_year_cleaned['Sex'] = sharks_q4_countries_and_year_cleaned['Sex'].replace("N", "No info")

In [1237]:
#3. 
sharks_q4_countries_and_year_cleaned_sex_is_lli = sharks_q4_countries_and_year_cleaned[sharks_q4_countries_and_year_cleaned["Sex"]=="lli"]
sharks_q4_countries_and_year_cleaned_sex_is_lli

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
1178,2004.11.11.b,11-Nov-2004,2004.0,Unprovoked,USA,California,"Bunkers, Humboldt Bay, Eureka, Humboldt County",Surfing,Brian Kang,lli,38,"Lacerations to hand, knee & thigh",N,13h30,5.5 m [18'] white shark,"R. Collier, GSAF",2004.11.11.b-Kang.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2004.11.11.b,2004.11.11.b,4679.0,NaN,NaN,Afternoon

In [1238]:
#it's a man according to PDF
sharks_q4_countries_and_year_cleaned['Sex'] = sharks_q4_countries_and_year_cleaned['Sex'].replace("lli", "M")
sharks_q4_countries_and_year_cleaned["Sex"].unique()

array(['F', 'M', nan], dtype=object)

In [1239]:
#4.
sharks_q4_countries_and_year_cleaned_sex_is_period = sharks_q4_countries_and_year_cleaned[sharks_q4_countries_and_year_cleaned["Sex"]=="."]
sharks_q4_countries_and_year_cleaned_sex_is_period

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex, Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23, Time of Day]
Index: []

In [1240]:
#it's several people. Assumption, this will fall under the category no info
sharks_q4_countries_and_year_cleaned['Sex'] = sharks_q4_countries_and_year_cleaned['Sex'].replace(".", "No info")
sharks_q4_countries_and_year_cleaned["Sex"].unique()

array(['F', 'M', nan], dtype=object)

In [1241]:
#5. Nan
sharks_q4_countries_and_year_cleaned_sex_is_na = sharks_q4_countries_and_year_cleaned[sharks_q4_countries_and_year_cleaned["Sex"].isna()]
sharks_q4_countries_and_year_cleaned_sex_is_na

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
533,2012.09.09,09-Sep-2012,2012.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,teen,NaN,19,Minor injury to elbow,N,14h20,NaN,"Daytona Beach News Journal, 9/9/2012",2012.09.09-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.09.09,2012.09.09,5563.0,NaN,NaN,Afternoon
558,2012.06.28.R,Reported 28-Jun-2012,2012.0,Invalid,CROATIA,NaN,Buccari Bay,Swimming,NaN,NaN,60,Leg struck. Initally reported as a shark attac...,NaN,NaN,No shark involvement,"Il Gazzettino, 6/28/2012",2012.06.28.R-Croatia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.06.28.R,2012.06.28.R,5532.0,NaN,NaN,Unknown
1277,2003.06.08,08-Jun-2003,2003.0,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,J.D.,NaN,15,6 puncture wounds to left ankle,N,11h55,NaN,"S. Petersohn, GSAF",2003.06.08-JD.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.06.08,2003.06.08,4533.0,NaN,NaN,Morning
1432,2001.04.10,10-Apr-2001,2001.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,a surfer from Port Orange,NaN,16,Foot lacerated,N,NaN,Possibly a juvenile blacktip or spinner shark,"Orlando Sentinel, 4/14/2001, p.A1",2001.04.10-PortOrangeSurfer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2001.04.10,2001.04.10,4340.0,NaN,NaN,Unknown
1453,2000.10.29,29-Oct-2000,2000.0,Boat,AUSTRALIA,Queensland,Peel Island,Fishing,"boat, occupant: Paul Kelly",NaN,31,"No Injury to occupant, shark holed and sank boat",N,22h00,White shark,"T. Peake, GSAF",2000.10.29-Kelly.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.10.29,2000.10.29,4308.0,NaN,NaN,Night
1624,1997.09.08,08-Sep-1997,1997.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,NaN,17,2 small lacerations to bottom of foot,N,Evening,small blacktip shark,"Daytona News-Journal, 9/9/1997",1997.09.08-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1997.09.08,1997.09.08,4078.0,NaN,NaN,Unknown
1690,1996.02.10.a,09-Feb-1996,1996.0,Unprovoked,PAPUA NEW GUINEA,Madang Province,Madang,Diving,schoolboy,NaN,14,Leg severed FATAL,Y,NaN,NaN,"Sunday Mail (QLD), 2/11/1996, p.28",1996.02.10.a-PNGschoolboy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1996.02.10.a,1996.02.10.a,3986.0,NaN,NaN,Unknown
1739,1995.05.31,31-May-1995,1995.0,Unprovoked,HONG KONG,New Territories,Sai Kung Beach,Diving,Tso Kam-Sun,NaN,44,"FATAL, right leg severed, left leg lacerated",Y,NaN,NaN,"J. Wong, GSAF; Daily Telegraph Mirror, 6/3/199...",1995.05.31-Tso.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1995.05.31,1995.05.31,3918.0,NaN,NaN,Unknown
1789,1993.09.16.b,16-Sep-1993,1993.0,Unprovoked,EL SALVADOR,La Libertad,near El Cocal Beach,Surfing,Jose Diter Roque,NaN,15,Left leg gashed,N,NaN,3.7 m [12'] white shark,"Tampa Tribune, 9/18/1993",1993.09.16.b-Roque.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1993.09.16.b,1993.09.16.b,3831.0,NaN,NaN,Unknown
1795,1993.08.19.R,Reported 19-Aug-1993,1993.0,Unprovoked,USA,Florida,"Bethune Beach, Volusia County",Surfing,Shawn Bushong,NaN,13,Right foot bitten,N,NaN,NaN,"Deseret News, 8/19/1993",1993.08.19.R-Bushong.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1993.08.19.R,1993.08.19.R,3825.0,NaN,NaN,Unknown
1815,1993.00.00.b,1993,1993.0,Unprovoked,TONGA,Vavau,Between Ofu & Fafini Islands,Spearfishing,A diver from Spain,NaN,30,Left buttock and thigh bitten,N,NaN,NaN,Drs. S. Fonea & A. Carafa,1993.00.00.b-Tonga.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1993.00.00.b,1993.00.00.b,3788.0,NaN,NaN,Unknown
2005,1986.09.00.a,Sep-1986,1986.0,Unprovoked,USA,Florida,"Ponce Inlet, New Smyrna Beach, Volusia County",Surfing,Anonymous,NaN,18,Hand bitten,N,NaN,NaN,Orlando Sentinel. 9/20/1986,1986.09.00.a-surfer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1986.09.00.a,1986.09.00.a,3493.0,NaN,NaN,Unknown
2006,1986.08.19,19-Aug-1986,1986.0,Unprovoked,USA,North Carolina,"Masonboro Inlet, New Hanover County",Surfing,J. McCorley,NaN,16,Hand bitten,N,NaN,NaN,"F. Schwartz, p.23",1986.08.19-McCorley.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1986.08.19,1986.08.19,3492.0,NaN,NaN,Unknown
2257,1975.03.13,13-Mar-1975,1975.0,Provoked,AUSTRALIA,Queensland,Southport Aquarium,Diving & force-feeding the shark,William Hookway,NaN,18,Laceration to thigh by captive shark PROVOKED ...,N,NaN,"Bronze whaler shark, 6'","The Age, 3/14/1975",1975.03.13-Hookway.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.03.13,1975.03.13,3068.0,NaN,NaN,Unknown
2264,1974.12.10,12-Dec-1974,1974.0,Unprovoked,AUSTRALIA,Western Australia,Geographe Bay,NaN,G. Allen,NaN,32,Survived,N,NaN,NaN,"J. Green, p.36",1974.12.10-Allen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1974.12.10,1974.12.10,3056.0,NaN,NaN,Unknown
2300,1973.08.27,27-Aug-1973,1973.0,Unprovoked,AUSTRALIA,Queensland,Palm Cove Beach,NaN,G. Cole,NaN,21,NaN,UNKNOWN,NaN,NaN,"J. Green, p.36",1973.08.27-Cole.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1973.08.27,1973.08.27,3005.0,NaN,NaN,Unknown
2306,1973.02.27,27-Feb-1973,1973.0,Unprovoked,MEXICO,Guerrero,"Revolcadero Beach, Acapulco",Swimming,Dr. Leo Ephraim Fischer,NaN,57,"FATAL, multiple bites",Y,NaN,NaN,"Reno Gazette, 4/8/1973; A.Resciniti, pp.108-109",1973.02.27-Ephraim.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1973.02.27,1973.02.27,2997.0,NaN,NaN,Unknown
2311,1972.12.08,08-Dec-1972,1972.0,Provoked,AUSTRALIA,New South Wales,"Marineland, Sydney",NaN,R. Bartlett,NaN,24,PROVOKED INCIDENT,N,NaN,NaN,"J. Green, p.36",1972.12.08-Bartlett.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1972.12.08,1972.12.08,2986.0,NaN,NaN,Unknown
2328,1971.12.23,23-Dec-1971,1971.0,Unprovoked,AUSTRALIA,New South Wales,Smokey Cape,NaN,G. Byron,NaN,22,Survived,N,NaN,NaN,"J. Green, p.36",1971.12.23-Byron.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1971.12.23,1971.12.23,2956.0,NaN,NaN,Unknown
2332,1971.11.25.R,27-Oct-1971,1971.0,Provoked,AUSTRALIA,New South Wales,"Marineland, Sydney",NaN,K. Tracy,NaN,20,PROVOKED INCIDENT,N,NaN,NaN,"J. Green, p.36",1971.11.25.R-Chan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1971.11.25.R,1971.11.25.R,2952.0,NaN,NaN,Unknown
2336,1971.09.25,25-Sep-1971,1971.0,Unprovoked,USA,North Carolina,"Emerald Isle, Carteret County",Surfing,J. Horner,NaN,17,Left foot injured,N,NaN,NaN,"F. Schwartz, p.23",1971.09.25-Horner.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1971.09.25,1971.09.25,2948.0,NaN,NaN,Unknown
2397,1968.08.11,11-Aug-1968,1968.0,Unprovoked,MALAYSIA,Johor,Pulau Aur,Leaving the water,Inche Bin Saini,NaN,41,Hand lacerated,N,08h00,NaN,"H.D.Baldridge, SAF Case #1541",1968.08.11-NV-InceBinSaini.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1968.08.11,1968.08.11,2841.0,NaN,NaN,Morning
2417,1968.02.00,Feb-1968,1968.0,Unprovoked,MOZAMBIQUE,NaN,NaN,Diving,Sergio Peres,NaN,24,No injury,N,NaN,NaN,H.D. Baldridge (1994) SAF Case #1522,1968.02.00-NV-Peres.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1968.02.00,1968.02.00,2816.0,NaN,NaN,Unknown
2418,1968.01.17,17-Jan-1968,1968.0,Unprovoked,PAPUA NEW GUINEA,Morobe Province,Finschafen,Swimming,Awin Ieromia,NaN,13,FATAL,Y,17h30,NaN,H.D. Baldridge (1994) SAF Cases #1519 & #1584,1968.01.17-NV-Ieromia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1968.01.17,1968.01.17,2815.0,NaN,NaN,Evening
2455,1966.11.14,14-Nov-1966,1966.0,Unprovoked,THAILAND,NaN,NaN,NaN,Vinit Tantikarn,NaN,28,No details,UNKNOWN,NaN,NaN,H.D. Baldridge (1994) SAF Case #1509,1966.11.14-NV-Tantikam.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1966.11.14,1966.11.14,2758.0,NaN,NaN,Unknown
2570,1963.09.26,26-Sep-1963,1963.0,Invalid,USA,Florida,100 miles offshore,"Commercial fishing vessel, Ev-nn, struck objec...","After 2 days, Ann Dumas, 7,5 months pregnant, ...",NaN,25,Numerous dusky sharks & a 3 m to 4.6 m [10' to...,NaN,NaN,Invalid,"Washington Post, 9/27/1963; SAF Case #1221",1963.09.26-Dumas.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1963.09.26,1963.09.26,2565.0,NaN,NaN,Unknown
2589,1963.01.14,14-Jan-1963,1963.0,Provoked,NEW ZEALAND,North Island,"Petone Beach, Wellington",Fishing,Ian Alexander,NaN,14,Minor lacerations to hand and arm after he sei...,N,Afternoon,"Grey nurse shark, 1.8 m [6']","R.D. Weeks, GSAF; Otago Daily Times, 1/15/1963...",1963.01.14-Alexander.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1963.01.14,1963.01.14,2535.0,NaN,NaN,Unknown
2724,1959.12.26,26-Dec-1959,1959.0,Unprovoked,PAPUA NEW GUINEA,Rigo subdistrict,Kaparoka,Swimming underneath house on pilings,Manama Mari,NaN,13,"FATAL, right leg severed",Y,NaN,NaN,"A. M. Rapson, p.150; P. Gilbert, L. Schultz & ...",1959.12.26-Mari.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1959.12.26,1959.12.26,2267.0,NaN,NaN,Unknown
2744,1959.07.25.a,25-Jul-1959,1959.0,Boat,USA,California,"Mission Beach, San Diego County",NaN,"boat, occupant Robert Agnew",NaN,21,No injury to occupant,N,NaN,"Hammerhead shark, 2.4 m [8']","San Diego Union, 7/26/1959",1959.07.25.a-Agnew.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1959.07.25.a,1959.07.25.a,2221.0,NaN,NaN,Unknown
2745,1959.07.03.a & b,03-Jul-1959,1959.0,Sea Disaster,PANAMA,PANAMA,"Off Cristobal, 200 miles northeast of the entr...",Columbian petrol barge Rio Atrato burned and sank,Teresea Britton (on raft) & a man (on floating...,NaN,27,"FATAL X 2, 8 others missing. Survivors fought ...",Y,NaN,NaN,"Cambridge Daily News, 7/4/1959; V. M. Coppleso...",1959.07.03-Rio-Atranto.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1959.07.03.a & b,1959.07.03.a & b,2218.0,NaN,NaN,Unknown
2894,1952.08.05,05-Aug-1952,1952.0,Provoked,ITALY,Teramo,Giulianova,Fishing,Vittorio Speca,NaN,19,Multiple injuries PROVOKED INCIDENT,Y,02h00,2m shark,"C. Moore, GSAF",1952.08.05-Speca.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1952.08.04,1952.08.05,1900.0,NaN,NaN,Night

In [1242]:
#I'll make use of the name column to try and get sum sauce:
nan_entries_in_sex = sharks_q4_countries_and_year_cleaned_sex_is_na.loc[sharks_q4_countries_and_year_cleaned_sex_is_na["Sex"].isna(), "Name"].unique()

nan_entries_in_sex

array(['teen', nan, 'J.D.', 'a surfer from Port Orange',
       'boat, occupant: Paul Kelly', 'male', 'schoolboy', 'Tso Kam-Sun',
       'Jose Diter Roque ', 'Shawn Bushong ', 'A diver from Spain',
       'Anonymous', 'J. McCorley', 'William Hookway', 'G. Allen',
       'G. Cole', 'Dr. Leo Ephraim Fischer', 'R. Bartlett', 'G. Byron',
       'K. Tracy', 'J. Horner', 'Inche Bin Saini', 'Sergio Peres',
       'Awin Ieromia', 'Vinit Tantikarn',
       'After 2 days, Ann Dumas, 7,5 months pregnant, died of exposure & exhaution& her body was lashed to raft.',
       'Ian Alexander', 'Manama Mari', 'boat, occupant Robert Agnew',
       'Teresea Britton (on raft) & a man (on floating debris)',
       'Vittorio Speca'], dtype=object)

In [1243]:
#array(['F', 'M', nan, 'No info'], dtype=object)


#OK let's do the dictionary trick again: I'll prioritize female entries since that's what's my analysis is going to consist of
correcting_where_sex_isna = {
    'Jeff Wells claimed he rescued his "daughter" from a 4 m tiger shark': 'F',
    'Nagisa Yasuhara': 'F',
    'Elena Hodgson & Isaac Ollis': 'F',
    'Teresea Britton (on raft) & a man (on floating debris)': 'F',
    '9 fishermen & pregnant woman': 'F',
    'After 2 days, Ann Dumas, 7,5 months pregnant, died of exposure & exhaution& her body was lashed to raft.': 'F',
    'Colleen Chamberlin & Scott Chamberlin': 'F',
    'skiboat Double One, occupants: Anton & Michelle Gets, Ray Whitaker, John & Lyn Palmer': 'F',
    "boat: 69.5' trawler Christy Nichole": 'F',
    'J. Graden': 'F',
}
    
    

#and now I replace these strange entries with the actual one:
sharks_q4_countries_and_year_cleaned.loc[sharks_q4_countries_and_year_cleaned['Name'].isin(correcting_where_sex_isna.keys()), 'Sex'] = sharks_q4_countries_and_year_cleaned['Sex'].map(correcting_type_based_on_activity_in_nan)

In [1244]:
sharks_q4_countries_and_year_cleaned

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3331,1830.07.26,26-Jul-1830,1830.0,Unprovoked,USA,Massachusetts,"Swampscott, Essex County","Fishing from dory, shark upset boat & he fell ...",Joseph Blaney,M,52,FATAL,Y,NaN,NaN,"Huron Sun, 8/3/1830",1830.07.26-JosephBlaney.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1830.07.26,1830.07.26,214.0,NaN,NaN,Unknown
3332,1828.09.28,28-Sep-1828,1828.0,Unprovoked,SIERRA LEONE,Western Area,"River Sierra Leone, 35 miles upriver from Fre...","British ship, Britannia, was loading lumber. ...","Thomas Corrigle, an apprentice from the ship",M,17,"Left arm severed 2.5"" from elbow, groin, abdom...",N,NaN,NaN,Account by J. Boyle,1828.09.28-Corrigle.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1828.09.28,1828.09.28,207.0,NaN,NaN,Unknown
3333,1817.05.11,11-May-1817,1817.0,Unprovoked,SRI LANKA,Western Province,Colombo,Swimming,William May,M,22,FATAL,Y,Evening,NaN,Edinburgh Advertiser. 11/4/1817; R. DeSilva,1817.05.11-May.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1817.05.11,1817.05.11,189.0,NaN,NaN,Unknown
3334,1749.00.00,1749,1749.0,Unprovoked,CUBA,Havana Province,Havana Harbor,Swimming,Brook Watson,M,14,Right leg severed at knee. In 1796 he became ...,N,NaN,NaN,GSAF,1749.00.00-Watson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1749.00.00,1749.00.00,151.0,NaN,NaN,Unknown
3335,1703.03.26,26-Mar-1703,1703.0,Unprovoked,BARBADOS,Southwest coast,Carlisle Bay,Swimming,"Samuel Jennings, a deserter from the British f...",M,19,"Hand and foot severely bitten, surgically ampu...",N,Night,NaN,"W.R.Cutter, Vol.1, p.252",1703.03.26-Jennings.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1703.03.26,1703.03.26,143.0,NaN,NaN,Unknown

In [1245]:
#for the remaining values, I see myself compelled to delete those entries:
sharks_q4_countries_and_year_cleaned = sharks_q4_countries_and_year_cleaned.dropna(subset=["Sex"])
sharks_q4_countries_and_year_cleaned

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3331,1830.07.26,26-Jul-1830,1830.0,Unprovoked,USA,Massachusetts,"Swampscott, Essex County","Fishing from dory, shark upset boat & he fell ...",Joseph Blaney,M,52,FATAL,Y,NaN,NaN,"Huron Sun, 8/3/1830",1830.07.26-JosephBlaney.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1830.07.26,1830.07.26,214.0,NaN,NaN,Unknown
3332,1828.09.28,28-Sep-1828,1828.0,Unprovoked,SIERRA LEONE,Western Area,"River Sierra Leone, 35 miles upriver from Fre...","British ship, Britannia, was loading lumber. ...","Thomas Corrigle, an apprentice from the ship",M,17,"Left arm severed 2.5"" from elbow, groin, abdom...",N,NaN,NaN,Account by J. Boyle,1828.09.28-Corrigle.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1828.09.28,1828.09.28,207.0,NaN,NaN,Unknown
3333,1817.05.11,11-May-1817,1817.0,Unprovoked,SRI LANKA,Western Province,Colombo,Swimming,William May,M,22,FATAL,Y,Evening,NaN,Edinburgh Advertiser. 11/4/1817; R. DeSilva,1817.05.11-May.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1817.05.11,1817.05.11,189.0,NaN,NaN,Unknown
3334,1749.00.00,1749,1749.0,Unprovoked,CUBA,Havana Province,Havana Harbor,Swimming,Brook Watson,M,14,Right leg severed at knee. In 1796 he became ...,N,NaN,NaN,GSAF,1749.00.00-Watson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1749.00.00,1749.00.00,151.0,NaN,NaN,Unknown
3335,1703.03.26,26-Mar-1703,1703.0,Unprovoked,BARBADOS,Southwest coast,Carlisle Bay,Swimming,"Samuel Jennings, a deserter from the British f...",M,19,"Hand and foot severely bitten, surgically ampu...",N,Night,NaN,"W.R.Cutter, Vol.1, p.252",1703.03.26-Jennings.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1703.03.26,1703.03.26,143.0,NaN,NaN,Unknown

# now: sharks_q4_countries_year_cleaned_and_sex_cleaned

In [1246]:
#finally making a cophy of the last dataframe!
sharks_q4_countries_year_cleaned_and_sex_cleaned = sharks_q4_countries_and_year_cleaned.copy()
#resetting the index and removing the duplicates:
sharks_q4_countries_year_cleaned_and_sex_cleaned = sharks_q4_countries_year_cleaned_and_sex_cleaned.reset_index(drop=True)
sharks_q4_countries_year_cleaned_and_sex_cleaned = sharks_q4_countries_year_cleaned_and_sex_cleaned.drop_duplicates(subset=['Case Number', 'Date', 'Country'], keep='first')
sharks_q4_countries_year_cleaned_and_sex_cleaned

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Time of Day
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,Evening
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,Afternoon
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,Morning
3,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN,Unknown
4,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3300,1830.07.26,26-Jul-1830,1830.0,Unprovoked,USA,Massachusetts,"Swampscott, Essex County","Fishing from dory, shark upset boat & he fell ...",Joseph Blaney,M,52,FATAL,Y,NaN,NaN,"Huron Sun, 8/3/1830",1830.07.26-JosephBlaney.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1830.07.26,1830.07.26,214.0,NaN,NaN,Unknown
3301,1828.09.28,28-Sep-1828,1828.0,Unprovoked,SIERRA LEONE,Western Area,"River Sierra Leone, 35 miles upriver from Fre...","British ship, Britannia, was loading lumber. ...","Thomas Corrigle, an apprentice from the ship",M,17,"Left arm severed 2.5"" from elbow, groin, abdom...",N,NaN,NaN,Account by J. Boyle,1828.09.28-Corrigle.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1828.09.28,1828.09.28,207.0,NaN,NaN,Unknown
3302,1817.05.11,11-May-1817,1817.0,Unprovoked,SRI LANKA,Western Province,Colombo,Swimming,William May,M,22,FATAL,Y,Evening,NaN,Edinburgh Advertiser. 11/4/1817; R. DeSilva,1817.05.11-May.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1817.05.11,1817.05.11,189.0,NaN,NaN,Unknown
3303,1749.00.00,1749,1749.0,Unprovoked,CUBA,Havana Province,Havana Harbor,Swimming,Brook Watson,M,14,Right leg severed at knee. In 1796 he became ...,N,NaN,NaN,GSAF,1749.00.00-Watson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1749.00.00,1749.00.00,151.0,NaN,NaN,Unknown
3304,1703.03.26,26-Mar-1703,1703.0,Unprovoked,BARBADOS,Southwest coast,Carlisle Bay,Swimming,"Samuel Jennings, a deserter from the British f...",M,19,"Hand and foot severely bitten, surgically ampu...",N,Night,NaN,"W.R.Cutter, Vol.1, p.252",1703.03.26-Jennings.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1703.03.26,1703.03.26,143.0,NaN,NaN,Unknown

In [1248]:
#exporting:
sharks_q4_countries_year_cleaned_and_sex_cleaned.to_csv('./data/Q4 attacks.csv', index=False)

In [1249]:
pwd

'C:\\Users\\mocid\\Ironhack\\labs\\projects\\Project1'